#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MAIN="$ROOT/app/src/main/java/com/kaleeb/wezterm/MainActivity.java"
MANIFEST="$ROOT/app/src/main/AndroidManifest.xml"
CONTROL_SERVER="${PHONE_CONTROL_SERVER:-$HOME/.local/bin/phone-terminal-control-server}"
PHONE_TERMINAL="${PHONE_TERMINAL:-$HOME/.local/bin/phone-terminal}"
PHONE_ADB_CONNECT="${PHONE_ADB_CONNECT:-$HOME/.local/bin/phone-adb-connect}"
README="$ROOT/README.md"
INSTALL_PAGE="$ROOT/build/install.html"
INSTALL_INDEX="$ROOT/build/index.html"
RUNTIME_PROOF="$ROOT/scripts/prove-phone-runtime-regression.sh"
MENU_UI_PROOF="$ROOT/scripts/prove-phone-menu-ui.sh"

require() {
    local file="$1"
    local pattern="$2"
    local message="$3"
    if ! grep -Fq -- "$pattern" "$file"; then
        echo "Phone plan regression guard failed: $message" >&2
        echo "Missing pattern: $pattern" >&2
        echo "File: $file" >&2
        exit 1
    fi
}

require_absent() {
    local file="$1"
    local pattern="$2"
    local message="$3"
    if grep -Fq -- "$pattern" "$file"; then
        echo "Phone plan regression guard failed: $message" >&2
        echo "Forbidden pattern: $pattern" >&2
        echo "File: $file" >&2
        exit 1
    fi
}

# WHY: this source-level audit is intentionally broad. The phone plan records a
# pattern of fixes regressing older fixes: scroll removing recovery, reconnect
# removing auto-reload, swipe fixes breaking typing, and toolbar cleanup hiding
# required controls. These cheap guards run before every APK build so a future
# edit cannot silently remove the protected behavior again.
require "$MANIFEST" 'android:versionName="1.53"' "current APK version must be bumped for the smooth down-scroll and direct upload fix"
require "$MANIFEST" 'android.intent.action.SEND' "WEzterm must remain an Android share target for screenshots/media"
require "$MANIFEST" 'android.intent.action.SEND_MULTIPLE' "WEzterm must accept multiple shared media files"
if [ -f "$README" ]; then
    # WHY: the APK can be correct while the public handoff still serves stale
    # install/proof text. Guard the docs that the phone actually opens so future
    # work cannot pass source checks while advertising an old build again.
    require "$README" 'Built checkpoint: `versionCode=54`, `versionName=1.53`.' "README checkpoint must match the installed v1.53 APK"
    require "$README" 'v1.46 adds a bounded ACTION_UP fling burst' "README must document the fast-flick physical-proof fix"
    require "$README" 'v1.48 collapses stacked focus/IME retry bursts' "README must document the duplicate-typing focus regression fix"
    require "$README" 'v1.49 marks every WebView load/reload as a new transport generation' "README must document the stale watchdog/reload regression fix"
    require "$README" 'v1.50 makes session titles wrap to full text' "README must document the full-title session picker fix"
    require "$README" 'v1.51 separates Active Sessions from Old Sessions' "README must document the Active/Old session picker fix"
    require "$README" 'v1.52 adds no-USB phone media uploads' "README must document the phone media upload fix"
    require "$README" 'v1.53 smooths the one-finger down-scroll return path' "README must document the down-scroll bottom-edge smoothing fix"
    require "$README" 'direct `Upload` toolbar button' "README must document the direct media upload toolbar button"
    require "$README" 'streams to disk with a 2 GB cap' "README must document video-safe media streaming"
    require "$README" 'Latest no-USB package proof used the Tailscale ADB relay' "README must document the no-USB proof path"
fi
if [ "${PHONE_SKIP_GENERATED_PAGE_GUARD:-0}" != "1" ] && [ -f "$INSTALL_PAGE" ]; then
    require "$INSTALL_PAGE" 'WEzterm v1.53' "install page must advertise the current v1.53 APK"
    require "$INSTALL_PAGE" 'versionCode: <code>54</code>' "install page versionCode must match the manifest"
    require "$INSTALL_PAGE" 'SHA-256: <code>' "install page must publish the built APK checksum"
    require "$INSTALL_PAGE" 'smooth down-scroll bottom-edge guards' "install page must mention the current down-scroll fix"
    require "$INSTALL_PAGE" 'direct Upload toolbar media' "install page must mention the direct upload toolbar fix"
    require "$INSTALL_PAGE" 'streaming video-safe phone uploads' "install page must mention the video-safe upload fix"
fi
if [ "${PHONE_SKIP_GENERATED_PAGE_GUARD:-0}" != "1" ] && [ -f "$INSTALL_INDEX" ]; then
    require "$INSTALL_INDEX" 'WEzterm v1.53 Install' "install redirect page must not point users at a stale version label"
fi
if [ -f "$RUNTIME_PROOF" ]; then
    require "$RUNTIME_PROOF" 'sessions activity groups' "runtime proof must check session/date picker data"
    require "$RUNTIME_PROOF" 'old parent sessions by date' "runtime proof must check old parent Codex sessions"
    require "$RUNTIME_PROOF" 'old sessions exclude subagents' "runtime proof must prove subagent sessions stay out"
    require "$RUNTIME_PROOF" 'resume-session dry-run' "runtime proof must check Old Sessions resume command without spawning a session"
    require "$RUNTIME_PROOF" 'needs-attention endpoint' "runtime proof must check Needs Attention data"
    require "$RUNTIME_PROOF" 'touch line up is tmux-owned' "runtime proof must check one-finger scroll routing"
    require "$RUNTIME_PROOF" 'extra down at live bottom stays stopped' "runtime proof must check bottom-edge down-scroll does not bounce"
    require "$RUNTIME_PROOF" 'paste endpoint' "runtime proof must check Copy/Paste paste route"
    require "$RUNTIME_PROOF" 'copy-visible endpoint' "runtime proof must check Copy/Paste copy route"
    require "$RUNTIME_PROOF" 'media upload endpoint' "runtime proof must check phone media upload route"
    require "$RUNTIME_PROOF" 'chunked media upload endpoint' "runtime proof must check video-style chunked media upload route"
    require "$RUNTIME_PROOF" 'stable windowId close' "runtime proof must check exact disposable-tab close"
    require "$RUNTIME_PROOF" 'restore original phone tab' "runtime proof must restore the user's tab"
fi
if [ -f "$MENU_UI_PROOF" ]; then
    require "$MENU_UI_PROOF" 'uiautomator dump' "menu UI proof must use the real installed phone UI"
    require "$MENU_UI_PROOF" 'for label in Active Old New Refresh Scroll "Copy/Paste" Upload Steer Close' "menu UI proof must check every bottom toolbar label"
    require "$MENU_UI_PROOF" 'tap_text "Old"' "menu UI proof must open Old Sessions"
    require "$MENU_UI_PROOF" 'assert_text "Old Sessions"' "menu UI proof must verify the Old Sessions dialog"
    require "$MENU_UI_PROOF" 'assert_text "Resume"' "menu UI proof must verify old-session resume actions"
    require "$MENU_UI_PROOF" 'New button created' "menu UI proof must prove New creates a disposable session"
    require "$MENU_UI_PROOF" 'Old Resume button opened' "menu UI proof must prove Old Sessions Resume opens a session"
    require "$MENU_UI_PROOF" 'Refresh button restored live mode' "menu UI proof must prove Refresh fixes the live view"
    require "$MENU_UI_PROOF" 'Page up' "menu UI proof must exercise Scroll Page up"
    require "$MENU_UI_PROOF" 'Page down' "menu UI proof must exercise Scroll Page down"
    require "$MENU_UI_PROOF" 'Go to live bottom / type' "menu UI proof must exercise live-bottom recovery"
    require "$MENU_UI_PROOF" 'Create bug report button created report' "menu UI proof must prove bug report button writes a report"
    require "$MENU_UI_PROOF" 'Install/update button launched external install surface' "menu UI proof must prove install button fires ACTION_VIEW"
    require "$MENU_UI_PROOF" 'Copy/Paste buttons round-tripped' "menu UI proof must prove Copy and Paste through Android clipboard plus tmux"
    require "$MENU_UI_PROOF" 'Steer button delivered Escape' "menu UI proof must prove Steer sends Escape"
    require "$MENU_UI_PROOF" 'Close button removed disposable session' "menu UI proof must prove Close removes only the disposable session"
    require "$MENU_UI_PROOF" 'orig_mode' "menu UI proof must preserve original tmux mode"
    require "$MENU_UI_PROOF" 'orig_scroll' "menu UI proof must preserve original tmux scroll position"
    require "$MENU_UI_PROOF" 'old-session date header' "menu UI proof must verify old sessions are grouped by date"
    require "$MENU_UI_PROOF" 'assert_absent "subagent"' "menu UI proof must prove subagent wording is absent from Old Sessions"
    require "$MENU_UI_PROOF" 'tap_text "Active"' "menu UI proof must open Active Sessions"
    require "$MENU_UI_PROOF" 'assert_text "Active Sessions"' "menu UI proof must verify Active Sessions"
    require "$MENU_UI_PROOF" 'tap_text "Command palette"' "menu UI proof must open the full menu"
    require "$MENU_UI_PROOF" 'assert_text "Needs Attention"' "menu UI proof must verify Needs Attention remains available"
    require "$MENU_UI_PROOF" 'assert_absent "Previous Sessions"' "menu UI proof must keep the confusing Previous Sessions label out"
    require "$MENU_UI_PROOF" 'tap_text "Copy/Paste"' "menu UI proof must open Copy/Paste"
    require "$MENU_UI_PROOF" 'assert_text "Upload media from phone"' "menu UI proof must verify the media upload control exists"
    require "$MENU_UI_PROOF" 'Phone menu UI button proof passed' "menu UI proof must have an explicit success marker"
else
    echo "Phone plan regression guard failed: scripts/prove-phone-menu-ui.sh is required" >&2
    exit 1
fi
require "$MAIN" 'toolbarButton("Active", v -> showActiveSessions())' "Active Sessions must remain on the main toolbar"
require "$MAIN" 'toolbarButton("Old", v -> showOldSessions())' "Old Sessions must remain on the main toolbar"
require "$MAIN" 'toolbarButton("New", v -> control("/new?fast=1", "New session opened"))' "New session must remain on the main toolbar"
require "$MAIN" 'toolbarButton("Refresh", v -> refreshTerminalTransport())' "Refresh must remain on the main toolbar"
require "$MAIN" 'toolbarButton("Scroll", v -> showViewControls())' "Scroll recovery menu must remain visible"
require "$MAIN" 'toolbarButton("Copy/Paste", v -> showCopyPasteControls())' "Copy/Paste must remain visible"
require "$MAIN" 'toolbarButton("Upload", v -> pickMediaForUpload())' "direct media Upload must remain visible on the main toolbar"
require "$MAIN" 'toolbarButton("Steer", v -> stopAndSteer())' "Steer/stop must remain visible"
require "$MAIN" 'toolbarButton("Close", v -> confirmClose())' "Close current session must remain visible"
require_absent "$MAIN" 'toolbarButton("Tabs"' "Tabs must not return as the primary phone wording; use Active Sessions"
require_absent "$MAIN" 'toolbarButton("New Tab"' "New Tab must not return as the primary phone wording; use New"
require_absent "$MAIN" 'toolbarButton("Close Tab"' "Close Tab must not return as the primary phone wording; use Close"
require_absent "$MAIN" 'toolbarButton("Live"' "Live must not be reintroduced as a main toolbar button without a new proven plan receipt"
require_absent "$MAIN" 'toolbarButton("Read"' "Read must not replace the visible Scroll recovery entry"
require_absent "$MAIN" 'toolbarButton("View"' "View must not replace the visible Scroll recovery entry"

require "$MAIN" '"Go to live bottom / type"' "Scroll menu must keep live-bottom/type recovery"
require "$MAIN" '"Command palette"' "Scroll menu must expose the command palette"
require "$MAIN" 'private void showCommandPalette()' "command palette method must remain implemented"
require "$MAIN" '"Refresh current session"' "command palette must expose refresh"
require "$MAIN" '"Active Sessions"' "command palette must expose Active Sessions"
require "$MAIN" '"Old Sessions"' "command palette must expose Old Sessions"
require "$MAIN" '"Needs Attention"' "command palette must expose Needs Attention"
require_absent "$MAIN" '"Sessions by date"' "old ambiguous sessions-by-date label must not return"
require_absent "$MAIN" '"Previous Sessions"' "Previous Sessions label must not return; user asked for Old Sessions"
require_absent "$MAIN" '"Needs attention"' "Needs Attention capitalization must stay consistent"
require "$MAIN" '"Create bug report"' "command palette must expose bug-report"
require "$MAIN" '"Install/update over Tailscale"' "command palette must expose no-USB install page"
require "$MAIN" '"Go to history top"' "Scroll menu must keep true-top recovery"
require "$MAIN" '"Read current session"' "Scroll menu must keep current-session reader"
require_absent "$MAIN" '"Open full session reader"' "old reader label must not return"
require "$MAIN" '"Page up"' "Scroll menu must keep page up"
require "$MAIN" '"Page down"' "Scroll menu must keep page down"
require "$MAIN" '"Stop current task"' "Scroll menu must keep stop fallback"
require "$MAIN" 'restoreLiveForTyping("At live bottom")' "live-bottom action must force the terminal back to typing"
require "$MAIN" 'restoreLiveForTyping("Opened " + title)' "tab selection must auto-return to live typing"
require "$MAIN" '"/select?fast=1&windowId="' "tab selection must target stable windowId"
require "$MAIN" '"/close?fast=1&windowId="' "close must target stable windowId"
require "$MAIN" 'getJson("/active"' "main Close must use active phone session metadata"
require "$MAIN" 'getJson("/sessions"' "Active/Old session pickers must use the session/date endpoint"
require "$MAIN" 'getJson("/needs-attention"' "Needs Attention must use the server endpoint"
require "$MAIN" 'payload.optString("viewSession"' "sessions UI must read phone view-session metadata"
require "$MAIN" 'activityGroup' "sessions UI must show date grouping metadata"
require "$MAIN" 'payload.optJSONArray("oldSessions")' "Old Sessions UI must render server oldSessions"
require "$MAIN" 'private void showOldSessionsDialog(JSONObject payload)' "Old Sessions dialog must remain implemented"
require "$MAIN" 'private int countOldSessionsForDate' "Old Sessions must group parent sessions by date"
require "$MAIN" 'private void confirmResumeOldSession' "Old Sessions must have a resume action"
require "$MAIN" '"/resume-session?fast=1&sessionId="' "Old Sessions must call the safe resume endpoint"
require "$MAIN" '!"user".equals(session.optString("threadSource", "user"))' "Old Sessions UI must filter non-user/subagent sessions"
require "$MAIN" 'Resume button is the action' "Old Sessions WHY comment must preserve date/name-only UI"
require "$MAIN" 'titleText.setSingleLine(false)' "session picker titles must wrap instead of truncating"
require "$MAIN" 'titleText.setMaxLines(Integer.MAX_VALUE)' "session picker titles must allow full title height"
require "$MAIN" 'titleText.setEllipsize(null)' "session picker titles must not ellipsize the title"
require "$MAIN" 'LinearLayout.LayoutParams.WRAP_CONTENT' "session picker rows must be allowed to grow with wrapped titles"
require "$MAIN" 'ClipData.newPlainText("WEzterm session title", title)' "full session title must be copyable from the phone"

require "$MAIN" 'ClipboardManager' "Copy/Paste must use Android clipboard APIs"
require "$MAIN" '"Paste phone clipboard into terminal"' "paste dialog option must remain"
require "$MAIN" '"Copy visible terminal text"' "copy dialog option must remain"
require "$MAIN" '"Upload media from phone"' "Copy/Paste menu must expose phone media upload"
require "$MAIN" 'copyPasteButton.setOnLongClickListener' "Copy/Paste long-press must keep a fast direct upload fallback"
require "$MAIN" 'Intent.ACTION_OPEN_DOCUMENT' "phone media upload must use Android's user-selected document picker"
require "$MAIN" 'Intent.ACTION_SEND' "phone media upload must handle Android share intents"
require "$MAIN" 'REQUEST_UPLOAD_MEDIA' "phone media picker result must remain wired"
require "$MAIN" 'MAX_MEDIA_UPLOAD_BYTES' "phone media upload must keep a file-size guard"
require "$MAIN" '2L * 1024L * 1024L * 1024L' "phone media upload must allow large video-sized files"
require "$MAIN" 'setFixedLengthStreamingMode(declaredSize)' "known-size media uploads must stream without buffering in Android heap"
require "$MAIN" 'setChunkedStreamingMode(MEDIA_UPLOAD_STREAM_CHUNK_BYTES)' "unknown-size media uploads must use chunked streaming instead of buffering"
require "$MAIN" 'streamUriToOutput' "Android media upload must stream from ContentResolver to HTTP output"
require_absent "$MAIN" 'readUriBytes' "Android media upload must not read whole videos into a byte array"
require "$MAIN" '"/upload-media?filename="' "phone media upload must post to the control server upload endpoint"
require "$MAIN" 'postText("/paste"' "paste must go through the control-server paste endpoint"
require "$MAIN" 'getJson("/copy-visible"' "copy must go through the control-server copy endpoint"

require "$MAIN" 'VelocityTracker' "slow-vs-fast flick behavior must keep Android velocity tracking"
require "$MAIN" 'HISTORY_DRAG_THROTTLE_MS = 28' "touch scroll must stay responsive enough to track a finger"
require "$MAIN" 'HISTORY_DRAG_LINE_THRESHOLD_DP = 10' "touch scroll must use line-sized movement threshold"
require "$MAIN" 'HISTORY_DRAG_PAGES_PER_STEP = 1' "slow scroll must stay controlled"
require "$MAIN" 'HISTORY_DRAG_MAX_PAGES_PER_STEP = 20' "fast flick must stay capped at the server-supported touch burst"
require "$MAIN" 'HISTORY_DRAG_DOWN_MAX_REPEATS = 4' "downward scroll batches must stay small near live bottom"
require "$MAIN" 'HISTORY_DRAG_DOWN_RELEASE_MAX_REPEATS = 4' "downward release flings must not reuse the large upward flick burst"
require "$MAIN" 'HISTORY_DRAG_FLING_VELOCITY_PX_PER_SEC' "fast flick threshold must remain explicit"
require "$MAIN" 'terminalTouchGestureGeneration' "touch scrolling must generation-cancel stale delayed responses"
require "$MAIN" 'pendingHistoryScrollGeneration' "pending touch scrolls must belong to the current gesture"
require "$MAIN" 'sendHistoryScrollFromTouch(where, boundedRepeats, gestureGeneration)' "touch scrolling must batch through bounded generation-tagged server repeats"
require "$MAIN" 'String where = step > 0 ? "lineUp" : "lineDown"' "touch scroll must use line-sized server movement, not page jumps"
require "$MAIN" 'scrollTerminalFromTouch(where, repeats)' "touch scroll must dispatch the explicit line-sized direction"
require "$MAIN" 'dispatchHistoryReleaseFling(event)' "fast flick must add a bounded ACTION_UP burst so it moves farther than slow drag"
require "$MAIN" 'one bounded release burst' "release-fling WHY comment must remain"
require "$MAIN" 'HISTORY_DRAG_RELEASE_FLING_BURSTS = 2' "full fling must keep the delayed second burst"
require "$MAIN" 'A second short-delay burst gives real fling velocity' "delayed fling-burst WHY comment must remain"
require "$MAIN" 'using one small batch and no delayed second burst' "downward flings must not queue the delayed second burst"
require "$MAIN" 'gestureGeneration != terminalTouchGestureGeneration' "stale touch-scroll replies must be ignored"
require "$MAIN" 'terminalTouchReachedLiveBottom' "touch scroll must remember the live-bottom edge during a drag"
require "$MAIN" 'touchScrollReachedLiveBottom' "touch scroll responses must exit read mode at the live bottom"
require "$MAIN" '"tmux-linedown".equals(payload.optString("action", ""))' "live-bottom detection must be restricted to tmux lineDown touch responses"
require "$MAIN" 'extra downward' "live-bottom edge WHY comment must prevent down-scroll bounce regressions"
require "$MAIN" '+ "&mode=touch&repeat="' "one-finger touch scroll must identify itself as tmux-style touch scroll"
require "$MAIN" 'showHistoryTouchOverlay()' "history/read mode overlay must keep swipes deterministic"
require "$MAIN" 'hideHistoryTouchOverlay()' "live typing must hide the history overlay"

require "$MAIN" 'pinTerminalViewportSoon' "old-tab viewport pin must remain"
require "$MAIN" 'document.scrollingElement' "WebView document scrolling must be pinned"
require "$MAIN" 'window.scrollTo(0,0)' "WebView viewport must be reset to the top-left"
require "$MAIN" 'view.setScrollContainer(false)' "WebView must not become the terminal scroll container"
require "$MAIN" 'view.setOverScrollMode(View.OVER_SCROLL_NEVER)' "WebView overscroll refresh effect must stay disabled"
require "$MAIN" 'WEBVIEW_ZOOMED_SCALE_THRESHOLD' "WebView zoom state must remain explicit"
require "$MAIN" 'private boolean isViewerPanAllowed()' "zoomed WebView panning must not be pinned away"
require "$MAIN" 'allowViewerPanBriefly()' "two-finger and horizontal viewer pan must unlock the WebView viewport"
require "$MAIN" 'public void onScaleChanged(WebView view, float oldScale, float newScale)' "Android/WebView zoom changes must be tracked"
require "$MAIN" 'Do not translate this' "WebView zoom must not be converted into tmux/font resize behavior"

require "$MAIN" 'terminalFocusAndReconnectProbeScript' "focus path must keep narrow reconnect overlay detection"
require "$MAIN" 'Press ↵ to Reconnect' "exact observed reconnect overlay must stay documented"
require "$MAIN" 'needsReconnect:overlay' "reconnect probe must return a machine-readable reconnect decision"
require "$MAIN" 'reloadTerminalForReconnect();' "detected reconnect overlay must auto-reload"
require "$MAIN" 'Pressing Enter here would send a real key' "synthetic Enter must remain forbidden"
require "$MAIN" 'TERMINAL_FOCUS_BURST_MIN_INTERVAL_MS' "focus retries must remain burst-collapsed"
require "$MAIN" 'terminalFocusGeneration' "stale focus callbacks must remain generation-cancelled"
require "$MAIN" 'generation != terminalFocusGeneration' "stale terminal focus callbacks must not run after newer focus"
require "$MAIN" 'LIVE_INPUT_VISIBILITY_BURST_MIN_INTERVAL_MS' "live-input visibility retries must remain burst-collapsed"
require "$MAIN" 'liveInputVisibilityGeneration' "stale live-input visibility callbacks must remain generation-cancelled"
require "$MAIN" 'KEYBOARD_SHOW_MIN_INTERVAL_MS' "Android IME show calls must remain throttled"
require "$MAIN" 'document.activeElement!==el' "xterm textarea focus must be a no-op when already active"
require "$MAIN" 'focus({preventScroll:true})' "xterm textarea focus must avoid WebView scroll jumps"
require "$MAIN" 'markTerminalLoadStarted()' "every WebView reload must invalidate stale focus/watchdog callbacks"
require "$MAIN" 'terminalFocusGeneration++' "WebView reloads must cancel stale focus callbacks"
require "$MAIN" 'liveInputVisibilityGeneration++' "WebView reloads must cancel stale visibility callbacks"
require "$MAIN" 'lastTerminalLoadAtMs = now' "blank-terminal watchdog must use explicit load generations"
require_absent "$MAIN" 'el.click()' "hidden xterm textarea click must not return; it duplicated input before"
require_absent "$MAIN" 'uiHandler.postDelayed(() -> focusTerminalInput(), 2400)' "old 2.4s unguarded focus retry must not return"

require "$MAIN" 'settings.setSupportZoom(true)' "pinch/zoom support must stay enabled"
require "$MAIN" 'settings.setBuiltInZoomControls(true)' "built-in WebView zoom must stay enabled"
require "$MAIN" 'settings.setDisplayZoomControls(false)' "old visible zoom controls must stay hidden"
require "$MAIN" 'WindowInsets.Type.ime()' "IME inset must be considered"
require "$MAIN" 'Math.max(bars.bottom, ime.bottom)' "toolbar must stay above nav bar or keyboard"
require "$MAIN" 'keepLiveInputVisibleSoon' "live typing must keep the xterm input visible above the keyboard"
require "$MAIN" 'scrollViewerToTypingPosition' "zoomed WebView must move down to the live input above the IME"
require_absent "$MAIN" 'Smaller text / zoom out' "terminal text-size controls must not masquerade as Android viewer zoom"
require_absent "$MAIN" 'Larger text / zoom in' "terminal text-size controls must not masquerade as Android viewer zoom"
require "$MAIN" 'private void refreshTerminalTransport()' "Refresh implementation must remain"
require "$MAIN" 'getJson("/fix-view"' "Refresh must ask the server to preserve/fix the active tmux view"
require "$MAIN" 'webView.loadUrl(currentUrl == null ? TERMINAL_URL : currentUrl)' "Refresh must reload only the WebView transport"
require "$MAIN" 'pinTerminalViewportSoon(reason)' "Refresh must repin WebView viewport"
require "$MAIN" 'scheduleBlankTerminalWatchdog(reason)' "Refresh must reuse blank-terminal watchdog"
require "$MAIN" 'private void openInstallPage()' "no-USB install page opener must remain"
require "$MAIN" 'new Intent(Intent.ACTION_VIEW, Uri.parse(INSTALL_URL))' "install page must open through Android ACTION_VIEW"
require "$MAIN" 'private void createBugReport()' "bug-report UI must remain implemented"
require "$MAIN" 'postText("/bug-report"' "bug-report UI must call the server endpoint"

if [ -f "$CONTROL_SERVER" ]; then
    require "$CONTROL_SERVER" 'parser.add_argument("--view-session", default="main_phone")' "control server must default to the phone view session"
    require "$CONTROL_SERVER" 'target = f"{self.active_target_session()}:{stable_id}"' "select must qualify stable windowId in the phone view"
    require "$CONTROL_SERVER" 'run_tmux("kill-window", "-t", target)' "close must kill the tmux window/process"
    require "$CONTROL_SERVER" 'repeat = max(1, min(repeat, 20))' "server scroll repeats must be capped"
    require "$CONTROL_SERVER" 'where in {"lineup", "upone"}' "server must preserve line-up touch scrolling"
    require "$CONTROL_SERVER" 'where in {"linedown", "downone"}' "server must preserve line-down touch scrolling"
    require "$CONTROL_SERVER" '"scroll-up"' "tmux touch scroll must use real copy-mode line scrolling"
    require "$CONTROL_SERVER" '"scroll-down"' "tmux touch scroll must use real copy-mode line scrolling"
    require "$CONTROL_SERVER" 'phone_touch_scroll = (request_mode or "").strip().lower() == "touch"' "one-finger phone touch scroll must bypass Codex transcript routing"
    require "$CONTROL_SERVER" '"atLiveBottom"] = True' "server must expose the tmux live-bottom edge to Android touch scroll"
    require "$CONTROL_SERVER" 'pane_in_copy_mode = run_tmux("display-message", "-p", "-t", target, "#{pane_in_mode}").strip() == "1"' "bottom after tmux touch-scroll must exit tmux copy-mode before Codex transcript routing"
    require "$CONTROL_SERVER" 'a desktop mouse wheel in tmux copy-mode' "touch-scroll intent comment must prevent Codex-history regressions"
    require "$CONTROL_SERVER" '"codexNoAltScreen"' "scroll layer must keep no-alt-screen Codex routing evidence"
    require "$CONTROL_SERVER" 'def codex_thread_id_from_open_files' "reader must infer npm-managed Codex thread IDs from open session files"
    require "$CONTROL_SERVER" 'def codex_thread_id_from_open_file_tree' "reader must walk from npm wrapper to native Codex process"
    require "$CONTROL_SERVER" '/.codex/sessions/' "reader open-file fallback must only inspect Codex session JSONL paths"
    require "$CONTROL_SERVER" 'payload.get("source") == "cli"' "reader open-file fallback must reject subagent source payloads"
    require "$CONTROL_SERVER" '"activityAt": activity_at' "tabs must expose activity ordering data"
    require "$CONTROL_SERVER" '"activityGroup": activity_group(activity_at)' "tabs must expose date grouping data"
    require "$CONTROL_SERVER" '"statusLabel": status["label"]' "tabs must expose running/done status labels"
    require "$CONTROL_SERVER" '"needsAttention": status["needsAttention"]' "tabs must expose needs-attention data"
    require "$CONTROL_SERVER" 'def recent_codex_sessions_from_state_db(limit):' "server must read old Codex session names from Codex state DB"
    require "$CONTROL_SERVER" "source = 'cli'" "old sessions must be limited to normal CLI sessions"
    require "$CONTROL_SERVER" "COALESCE(thread_source, 'user') = 'user'" "old sessions must exclude subagent threads"
    require "$CONTROL_SERVER" "COALESCE(agent_nickname, '') = ''" "old sessions must exclude named subagents"
    require "$CONTROL_SERVER" 'payload.get("agent_nickname")' "old-session JSONL fallback must also exclude named subagents"
    require "$CONTROL_SERVER" '"dateLabel": date_label_from_timestamp' "old sessions must expose exact date labels"
    require "$CONTROL_SERVER" 'payload["oldSessions"] = old_sessions' "server must expose explicit oldSessions payload"
    require "$CONTROL_SERVER" 'payload["recentCodexSessions"] = old_sessions' "server must keep recentCodexSessions compatibility alias"
    require "$CONTROL_SERVER" 'def resume_session(self, session_id, cwd="", include_tabs=True, dry_run=False):' "server must implement safe old-session resume"
    require "$CONTROL_SERVER" '"action": "resume-dry-run"' "server must support safe resume dry-run proof"
    require "$CONTROL_SERVER" 'exec codex --no-alt-screen resume' "old-session resume must use no-alt-screen Codex resume"
    require "$CONTROL_SERVER" 'elif parsed.path == "/resume-session":' "GET /resume-session route must remain"
    require "$CONTROL_SERVER" 'def sessions(self):' "server sessions endpoint must remain implemented"
    require "$CONTROL_SERVER" 'def needs_attention(self):' "server needs-attention endpoint must remain implemented"
    require "$CONTROL_SERVER" 'def fix_view(self):' "server fix-view endpoint must remain implemented"
    require "$CONTROL_SERVER" 'def bug_report(self, body=""):' "server bug-report endpoint must remain implemented"
    require "$CONTROL_SERVER" 'elif parsed.path == "/sessions":' "GET /sessions route must remain"
    require "$CONTROL_SERVER" 'elif parsed.path == "/needs-attention":' "GET /needs-attention route must remain"
    require "$CONTROL_SERVER" 'elif parsed.path == "/fix-view":' "GET /fix-view route must remain"
    require "$CONTROL_SERVER" 'elif parsed.path == "/bug-report":' "bug-report route must remain"
    require "$CONTROL_SERVER" 'def paste_text(self, text):' "server paste endpoint must remain implemented"
    require "$CONTROL_SERVER" 'load-buffer", "-b", "phone-paste", "-"' "paste must load tmux buffer from stdin"
    require "$CONTROL_SERVER" 'paste-buffer", "-d", "-p", "-b", "phone-paste"' "paste must use tmux paste-buffer"
    require "$CONTROL_SERVER" 'def copy_visible(self):' "server copy-visible endpoint must remain implemented"
    require "$CONTROL_SERVER" 'MAX_UPLOAD_BYTES' "server media uploads must keep a size cap"
    require "$CONTROL_SERVER" '2 * 1024 * 1024 * 1024' "server media upload cap must allow video-sized files"
    require "$CONTROL_SERVER" 'UPLOAD_READ_CHUNK_BYTES' "server media uploads must stream to disk in bounded chunks"
    require "$CONTROL_SERVER" 'def safe_upload_filename' "server media upload filenames must be sanitized"
    require "$CONTROL_SERVER" 'def upload_media_stream(self, filename, content_type, stream, length=None, chunked=False):' "server media upload endpoint must stream request bodies"
    require "$CONTROL_SERVER" 'def _copy_chunked_upload_to_file' "server must accept chunked streaming uploads from Android unknown-size media"
    require "$CONTROL_SERVER" 'Transfer-Encoding' "server upload route must detect chunked transfer encoding"
    require "$CONTROL_SERVER" '~/phone-uploads' "server media upload must save to the desktop phone-uploads folder"
    require "$CONTROL_SERVER" 'elif parsed.path == "/copy-visible":' "GET /copy-visible route must remain"
    require "$CONTROL_SERVER" 'parsed.path == "/upload-media"' "POST /upload-media route must remain"
    require "$CONTROL_SERVER" 'if parsed.path == "/paste":' "POST /paste route must remain"
    require "$CONTROL_SERVER" 'def stop(self):' "server stop endpoint must remain implemented"
    require "$CONTROL_SERVER" 'run_tmux("send-keys", "-t", target, "Escape")' "Stop/Steer must still send Escape"
fi

if [ -f "$PHONE_TERMINAL" ]; then
    require "$PHONE_TERMINAL" 'PHONE_TITLE_SYNC_ENABLED:-1' "title sync should remain enabled by default"
    require "$PHONE_TERMINAL" 'scrollback=$PHONE_SCROLLBACK' "ttyd scrollback must use the configurable large cap"
    require "$PHONE_TERMINAL" '--client-option rendererType=canvas' "ttyd must keep canvas renderer"
    require "$PHONE_TERMINAL" '--client-option scrollOnUserInput=true' "ttyd must keep scroll-on-input behavior"
fi

if [ -f "$PHONE_ADB_CONNECT" ]; then
    require "$PHONE_ADB_CONNECT" 'Tailscale relay is online: ${RELAY_HOST}:${RELAY_PORT} -> ${PHONE_TAILSCALE_IP}:5555' "no-USB Tailscale relay proof path must remain"
    require "$PHONE_ADB_CONNECT" 'phone-adb-connect install [ADB_SERIAL] [APK_PATH]' "no-USB install helper must remain documented"
    require "$PHONE_ADB_CONNECT" 'install_apk()' "no-USB install helper must remain implemented"
    require "$PHONE_ADB_CONNECT" '127.0.0.1' "relay must keep localhost ADB target"
    require "$PHONE_ADB_CONNECT" 'PHONE_TAILSCALE_IP' "relay must remain Tailscale-backed"
fi

require "$ROOT/build-apk.sh" 'sha256sum build/WEzterm.apk' "build must derive the install page checksum from the signed APK"
require "$ROOT/build-apk.sh" 'cat > build/install.html' "build must regenerate the public install page after signing"
require "$ROOT/build-apk.sh" 'WEzterm v${VERSION_NAME}' "build-generated install page must use the manifest version"

require "$ROOT/scripts/prove-phone-runtime-regression.sh" 'old session JSONL fallback filter' "runtime proof must force the old-session JSONL fallback filter"
require "$ROOT/scripts/prove-phone-runtime-regression.sh" 'touch top reaches tmux history top' "runtime proof must keep true-top tmux scroll coverage"
require "$ROOT/scripts/prove-phone-menu-ui.sh" 'Read current session opened reader' "UI proof must exercise the reader button"
require "$ROOT/scripts/prove-phone-menu-ui.sh" 'Physical one-finger slow/fast scroll proved' "UI proof must exercise physical slow-vs-fast swipe behavior"
require "$ROOT/scripts/prove-phone-menu-ui.sh" 'terminal screenshot text pixels' "UI proof must pixel-check Refresh repaint"
require "$ROOT/scripts/prove-phone-menu-ui.sh" 'Tap-to-type delivered one visible token' "UI proof must exercise tap-to-type without duplicate input"

echo "Phone plan regression guard passed"
