#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MAIN="$ROOT/app/src/main/java/com/kaleeb/wezterm/MainActivity.java"
MANIFEST="$ROOT/app/src/main/AndroidManifest.xml"
CONTROL_SERVER="${PHONE_CONTROL_SERVER:-$HOME/.local/bin/phone-terminal-control-server}"
PHONE_TERMINAL="${PHONE_TERMINAL:-$HOME/.local/bin/phone-terminal}"
PHONE_ADB_CONNECT="${PHONE_ADB_CONNECT:-$HOME/.local/bin/phone-adb-connect}"
README="$ROOT/README.md"
INSTALL_PAGE="$ROOT/build/install.html"
INSTALL_INDEX="$ROOT/build/index.html"
RUNTIME_PROOF="$ROOT/scripts/prove-phone-runtime-regression.sh"
MENU_UI_PROOF="$ROOT/scripts/prove-phone-menu-ui.sh"
APPLE_DOC="$ROOT/docs/apple-users.md"
MACOS_PREFLIGHT="$ROOT/scripts/macos-host-preflight.sh"

require() {
    local file="$1"
    local pattern="$2"
    local message="$3"
    if ! grep -Fq -- "$pattern" "$file"; then
        echo "Phone plan regression guard failed: $message" >&2
        echo "Missing pattern: $pattern" >&2
        echo "File: $file" >&2
        exit 1
    fi
}

require_absent() {
    local file="$1"
    local pattern="$2"
    local message="$3"
    if grep -Fq -- "$pattern" "$file"; then
        echo "Phone plan regression guard failed: $message" >&2
        echo "Forbidden pattern: $pattern" >&2
        echo "File: $file" >&2
        exit 1
    fi
}

# WHY: this source-level audit is intentionally broad. The phone plan records a
# pattern of fixes regressing older fixes: scroll removing recovery, reconnect
# removing auto-reload, swipe fixes breaking typing, and toolbar cleanup hiding
# required controls. These cheap guards run before every APK build so a future
# edit cannot silently remove the protected behavior again.
require "$MANIFEST" 'android:versionCode="72"' "current APK version must be bumped for the Active Sessions action-row hotfix"
require "$MANIFEST" 'android:versionName="1.71"' "current APK version must be bumped for the Active Sessions action-row hotfix"
require "$MANIFEST" 'android:windowSoftInputMode="adjustResize"' "activity must resize for IME without activity-start keyboard forcing"
require_absent "$MANIFEST" 'stateVisible|adjustResize' "activity-start IME forcing must not return"
require "$MANIFEST" 'android.intent.action.SEND' "WEzterm must remain an Android share target for screenshots/media"
require "$MANIFEST" 'android.intent.action.SEND_MULTIPLE' "WEzterm must accept multiple shared media files"
if [ -f "$README" ]; then
    # WHY: the APK can be correct while the public handoff still serves stale
    # install/proof text. Guard the docs that the phone actually opens so future
    # work cannot pass source checks while advertising an old build again.
    require "$README" 'Built checkpoint: `versionCode=72`, `versionName=1.71`.' "README checkpoint must match the installed v1.71 APK"
    require "$README" 'v1.46 adds a bounded ACTION_UP fling burst' "README must document the fast-flick physical-proof fix"
    require "$README" 'v1.48 collapses stacked focus/IME retry bursts' "README must document the duplicate-typing focus regression fix"
    require "$README" 'v1.49 marks every WebView load/reload as a new transport generation' "README must document the stale watchdog/reload regression fix"
    require "$README" 'v1.50 makes session titles wrap to full text' "README must document the full-title session picker fix"
    require "$README" 'v1.51 separates Active Sessions from Old Sessions' "README must document the Active/Old session picker fix"
    require "$README" 'v1.52 adds no-USB phone media uploads' "README must document the phone media upload fix"
    require "$README" 'v1.53 smooths the one-finger down-scroll return path' "README must document the down-scroll bottom-edge smoothing fix"
    require "$README" 'v1.54 removes the ambiguous combined interrupt/send action' "README must document the Start/Stop split"
    require "$README" 'lightweight `/touch-scroll` server path' "README must document the low-latency touch-scroll path"
    require "$README" 'opens new phone-created sessions in `/home/cabule`' "README must document the new-session cwd fix"
    require "$README" 'v1.55 restores phone voice input' "README must document the voice-input IME hotfix"
    require "$README" 'v1.55 tried to make Active Sessions switching repaint the phone immediately' "README must document the active-switch repaint attempt"
    require "$README" 'v1.56 removed the automatic gesture-end live-bottom restore' "README must document the bottom-refresh loop fix"
    require "$README" 'v1.57 exits tmux copy-mode quietly at one-finger live bottom' "README must document the quiet touch-bottom fix"
    require "$README" 'v1.57 removes the WebView reload from Active Sessions switching' "README must document the no-reload Active switch fix"
    require "$README" 'v1.57 also moves normal `Scroll -> Go to live bottom / type`' "README must document the fast live-bottom no-refresh fix"
    require "$README" 'v1.57 makes the visible `Scroll` dialog scroll-only again' "README must document the scroll-only menu fix"
    require "$README" 'v1.57 makes passive Android lifecycle callbacks passive' "README must document the passive focus/page-finished fix"
    require "$README" 'v1.58 makes tap-to-type a single keyboard focus burst' "README must document the duplicate typing focus hotfix"
    require "$README" 'v1.59 increases the one-finger downward return-to-live cap' "README must document the downward return speed hotfix"
    require "$README" 'v1.60 raises the downward return cap to the control server' "README must document the 20-line downward return speed hotfix"
    require "$README" 'v1.61 treats a tiny tmux `lineDown` remainder as the live-bottom edge' "README must document the near-bottom restore hotfix"
    require "$README" 'v1.62 widens that quiet near-bottom restore band to 16 lines' "README must document the v1.62 near-bottom threshold"
    require "$README" 'v1.63 removes the unconditional delayed keyboard retry from tap-to-type' "README must document the duplicate typing retry hotfix"
    require "$README" 'v1.64 removes activity-start keyboard requests and guards late generic control callbacks' "README must document the duplicate typing IME hotfix"
    require "$README" 'v1.65 makes terminal-body taps single-owner' "README must document the body-tap duplicate typing hotfix"
    require "$README" 'v1.66 moves normal phone typing into a docked native composer' "README must document the native composer duplicate typing hotfix"
    require "$README" 'v1.67 removes the stale hidden composer action row' "README must document the hidden composer row cleanup"
    require "$README" 'v1.68 refits ttyd/xterm after Android WebView layout changes' "README must document the zoomed bottom/full-area hotfix"
    require "$README" 'v1.69 makes plain toolbar buttons consume their own in-bounds tap' "README must document the Active toolbar tap reliability hotfix"
    require "$README" 'v1.70 pins the current active tmux window at the top of Active Sessions' "README must document the current-first Active Sessions hotfix"
    require "$README" 'v1.71 moves the Active Sessions actions into a compact in-dialog row' "README must document the Active Sessions action-row hotfix"
    require "$README" 'full multi-word phone clipboard paste' "README must document the full-text clipboard paste proof"
    require "$README" 'direct `Bottom` toolbar button' "README must document the direct bottom button"
    require "$README" 'keeps keyboard height out of' "README must document the toolbar/IME height hotfix"
    require "$README" "the toolbar's own layout height" "README must document that keyboard height is not toolbar height"
    require "$README" 'two rows with ripple/tap feedback' "README must document the toolbar feedback/readability fix"
    require "$README" 'direct `Upload` toolbar button' "README must document the direct media upload toolbar button"
    require "$README" 'streams to disk with a 2 GB cap' "README must document video-safe media streaming"
    require "$README" 'Latest no-USB package proof used the Tailscale ADB relay' "README must document the no-USB proof path"
    require "$README" 'Apple User Support' "README must document the Apple/macOS support path"
    require "$README" 'tmux runs on macOS' "README must not imply tmux is Linux-only"
    require "$README" 'Safari/Add to Home Screen' "README must explain the iOS client path"
fi
if [ -f "$APPLE_DOC" ]; then
    require "$APPLE_DOC" 'Mac as the terminal host' "Apple doc must support Mac host users"
    require "$APPLE_DOC" 'iPhone or iPad as the client' "Apple doc must explain iOS client users"
    require "$APPLE_DOC" 'brew install tmux ttyd tailscale python' "Apple doc must include Homebrew dependency install"
    require "$APPLE_DOC" 'tmux is the persistence boundary' "Apple doc must preserve the tmux architecture reason"
    require "$APPLE_DOC" 'Do not tell iPhone users to install the Android APK' "Apple doc must prevent Android APK/iOS confusion"
fi
if [ -f "$MACOS_PREFLIGHT" ]; then
    require "$MACOS_PREFLIGHT" 'uname -s' "macOS preflight must verify it is running on Darwin"
    require "$MACOS_PREFLIGHT" 'brew install tmux ttyd tailscale python' "macOS preflight must give one Homebrew install hint"
    require "$MACOS_PREFLIGHT" 'tailscale ip -4' "macOS preflight must prove Tailnet reachability"
    require "$MACOS_PREFLIGHT" 'tmux new-session -d -s "$TMUX_SESSION"' "macOS preflight must create/reuse the phone tmux session"
    require "$MACOS_PREFLIGHT" 'ttyd --interface ${tailnet_ip} --port 8088 tmux attach -t ${TMUX_SESSION}' "macOS preflight must print the fast ttyd host command"
fi
if [ "${PHONE_SKIP_GENERATED_PAGE_GUARD:-0}" != "1" ] && [ -f "$INSTALL_PAGE" ]; then
    require "$INSTALL_PAGE" 'WEzterm v1.71' "install page must advertise the current v1.71 APK"
    require "$INSTALL_PAGE" 'versionCode: <code>72</code>' "install page versionCode must match the manifest"
    require "$INSTALL_PAGE" 'SHA-256: <code>' "install page must publish the built APK checksum"
    require "$INSTALL_PAGE" 'no-refresh bottom-edge scroll guards' "install page must mention the current no-refresh down-scroll fix"
    require "$INSTALL_PAGE" 'direct Upload toolbar media' "install page must mention the direct upload toolbar fix"
    require "$INSTALL_PAGE" 'streaming video-safe phone uploads' "install page must mention the video-safe upload fix"
    require "$INSTALL_PAGE" 'separate Start/Stop controls' "install page must mention the Start/Stop split"
    require "$INSTALL_PAGE" 'voice dictation' "install page must mention the voice-input fix"
    require "$INSTALL_PAGE" 'no-reload Active switching' "install page must mention the Active Sessions no-reload fix"
    require "$INSTALL_PAGE" 'one-tap Active title switching' "install page must mention one-tap Active row switching"
    require "$INSTALL_PAGE" 'deterministic plain toolbar taps' "install page must mention the Active toolbar tap reliability fix"
    require "$INSTALL_PAGE" 'current-first Active Sessions' "install page must mention the current-first Active Sessions fix"
    require "$INSTALL_PAGE" 'compact Active Sessions action row' "install page must mention the Active Sessions action-row fix"
    require "$INSTALL_PAGE" 'scroll-only Scroll menu' "install page must mention the scroll-only Scroll menu fix"
    require "$INSTALL_PAGE" 'fast no-refresh live-bottom typing recovery' "install page must mention the fast live-bottom route"
    require "$INSTALL_PAGE" 'passive upload/page-finished focus guards' "install page must mention passive upload/page-finished focus guards"
    require "$INSTALL_PAGE" 'native composer typing' "install page must mention the duplicate typing native composer hotfix"
    require "$INSTALL_PAGE" 'no direct WebView IME typing for terminal-body taps' "install page must mention direct WebView IME typing is disabled"
    require "$INSTALL_PAGE" 'no activity-start IME request' "install page must mention the no-implicit-IME hotfix"
    require "$INSTALL_PAGE" 'late-control IME guard' "install page must mention the late-control focus guard"
    require "$INSTALL_PAGE" '20-line bounded downward return' "install page must mention the downward return speed hotfix"
    require "$INSTALL_PAGE" '16-line near-bottom quiet restore' "install page must mention the near-bottom restore hotfix"
    require "$INSTALL_PAGE" 'quiet touch-bottom copy-mode exit' "install page must mention quiet one-finger bottom restore"
    require "$INSTALL_PAGE" 'two-row toolbar tap feedback' "install page must mention visible tap feedback"
    require "$INSTALL_PAGE" 'safe control retry' "install page must mention bounded control retry"
    require "$INSTALL_PAGE" 'lightweight tmux touch-scroll gestures' "install page must mention the low-latency touch-scroll fix"
    require "$INSTALL_PAGE" 'native composer typing' "install page must mention the native composer typing fix"
    require "$INSTALL_PAGE" 'full multi-word clipboard paste' "install page must mention full-text Copy/Paste proof"
    require "$INSTALL_PAGE" 'direct Bottom button' "install page must mention the direct bottom button"
    require "$INSTALL_PAGE" 'zoomed true-bottom viewer reach' "install page must mention the zoomed bottom/full-area fix"
fi
if [ "${PHONE_SKIP_GENERATED_PAGE_GUARD:-0}" != "1" ] && [ -f "$INSTALL_INDEX" ]; then
    require "$INSTALL_INDEX" 'WEzterm v1.71 Install' "install redirect page must not point users at a stale version label"
fi
if [ -f "$RUNTIME_PROOF" ]; then
    require "$RUNTIME_PROOF" 'sessions activity groups' "runtime proof must check session/date picker data"
    require "$RUNTIME_PROOF" 'old parent sessions by date' "runtime proof must check old parent Codex sessions"
    require "$RUNTIME_PROOF" 'old sessions exclude subagents' "runtime proof must prove subagent sessions stay out"
    require "$RUNTIME_PROOF" 'resume-session dry-run' "runtime proof must check Old Sessions resume command without spawning a session"
    require "$RUNTIME_PROOF" 'needs-attention endpoint' "runtime proof must check Needs Attention data"
    require "$RUNTIME_PROOF" 'touch-scroll endpoint' "runtime proof must check one-finger scroll routing"
    require "$RUNTIME_PROOF" 'extra down at live bottom stays stopped' "runtime proof must check bottom-edge down-scroll does not bounce"
    require "$RUNTIME_PROOF" 'paste endpoint full text' "runtime proof must check Copy/Paste paste route with spaces"
    require "$RUNTIME_PROOF" 'copy-visible endpoint' "runtime proof must check Copy/Paste copy route"
    require "$RUNTIME_PROOF" 'media upload endpoint' "runtime proof must check phone media upload route"
    require "$RUNTIME_PROOF" 'chunked media upload endpoint' "runtime proof must check video-style chunked media upload route"
    require "$RUNTIME_PROOF" 'new session cwd is /home/cabule' "runtime proof must check phone New opens in /home/cabule"
    require "$RUNTIME_PROOF" 'select-live endpoint' "runtime proof must check fast Active Sessions switching"
    require "$RUNTIME_PROOF" 'live-bottom fast endpoint' "runtime proof must check the fast no-refresh live-bottom route"
    require "$RUNTIME_PROOF" 'touch-scroll endpoint' "runtime proof must check low-latency one-finger scroll routing"
    require "$RUNTIME_PROOF" 'send-enter endpoint' "runtime proof must check Start/Enter route"
    require "$RUNTIME_PROOF" 'submit-text endpoint' "runtime proof must check safe native prompt route"
    require "$RUNTIME_PROOF" 'stop endpoint double escape' "runtime proof must check Stop route"
    require "$RUNTIME_PROOF" 'stable windowId close' "runtime proof must check exact disposable-tab close"
    require "$RUNTIME_PROOF" 'restore original phone tab' "runtime proof must restore the user's tab"
fi
if [ -f "$MENU_UI_PROOF" ]; then
    require "$MENU_UI_PROOF" 'uiautomator dump' "menu UI proof must use the real installed phone UI"
    require "$MENU_UI_PROOF" 'phone menu UI proof failed at line' "menu UI proof must report exact failing commands instead of silent exits"
    require "$MENU_UI_PROOF" 'for label in Active Old New Refresh Bottom Scroll "Copy/Paste" Upload Close Start Stop' "menu UI proof must check every bottom toolbar label"
    require "$MENU_UI_PROOF" 'tap_text "Old"' "menu UI proof must open Old Sessions"
    require "$MENU_UI_PROOF" 'assert_text "Old Sessions"' "menu UI proof must verify the Old Sessions dialog"
    require "$MENU_UI_PROOF" 'assert_text "Resume"' "menu UI proof must verify old-session resume actions"
    require "$MENU_UI_PROOF" 'New button created' "menu UI proof must prove New creates a disposable session"
    require "$MENU_UI_PROOF" 'Old Resume button opened' "menu UI proof must prove Old Sessions Resume opens a session"
    require "$MENU_UI_PROOF" 'Refresh button restored live mode' "menu UI proof must prove Refresh fixes the live view"
    require "$MENU_UI_PROOF" 'Page up' "menu UI proof must exercise Scroll Page up"
    require "$MENU_UI_PROOF" 'Page down' "menu UI proof must exercise Scroll Page down"
    require "$MENU_UI_PROOF" 'Go to live bottom / type' "menu UI proof must exercise live-bottom recovery"
    require "$MENU_UI_PROOF" 'open_scroll_menu()' "menu UI proof must robustly open the scroll-only menu from toolbar state"
    require "$MENU_UI_PROOF" 'Direct Bottom button returned to live typing' "menu UI proof must exercise the one-tap Bottom toolbar button"
    require "$MENU_UI_PROOF" 'Terminal and toolbar bounds do not overlap' "menu UI proof must prove toolbar buttons do not cover the terminal bottom"
    require "$MENU_UI_PROOF" 'Scroll menu is scroll-only' "menu UI proof must prove Scroll is not the old giant controls menu"
    require "$MENU_UI_PROOF" 'Active row title switched with one tap' "menu UI proof must tap an Active title row exactly once"
    require "$MENU_UI_PROOF" 'assert_text "Rename"' "menu UI proof must verify the Active Sessions compact action row"
    require "$MENU_UI_PROOF" 'dragging the finger down moves into older tmux history' "menu UI proof must document the protected physical swipe direction"
    require "$MENU_UI_PROOF" 'terminal_swipe()' "physical scroll proof must compute real terminal bounds instead of hardcoded portrait coordinates"
    require "$MENU_UI_PROOF" 'terminal_tap_for_typing()' "tap-to-type proof must compute real terminal bounds instead of hardcoded portrait coordinates"
    require "$MENU_UI_PROOF" 'resource_id == "terminal-container"' "physical scroll proof must prefer the actual terminal container bounds"
    require "$MENU_UI_PROOF" 'terminal_swipe history-slow 900' "slow physical scroll proof must drag finger down from live bottom into history"
    require "$MENU_UI_PROOF" 'terminal_swipe history-fast 120' "fast physical scroll proof must flick finger down into older history"
    require "$MENU_UI_PROOF" 'terminal_swipe live-return 250' "live-bottom physical proof must drag finger up toward the live bottom"
    require "$MENU_UI_PROOF" 'live_return_mode="$(tmux_window_pane_mode "$proof_window")"' "live-bottom proof must treat the explicit proof window's tmux mode as the primary live-bottom signal"
    require "$MENU_UI_PROOF" '[ -n "$live_return_scroll" ]' "live-bottom proof must allow tmux live mode's blank scroll_position"
    require "$MENU_UI_PROOF" 'Physical one-finger live-bottom exited copy-mode quietly' "menu UI proof must prove one-finger down-scroll reaches live bottom"
    require "$MENU_UI_PROOF" 'Native composer opened from terminal tap' "menu UI proof must prove terminal taps open the native composer"
    require "$MENU_UI_PROOF" 'Native composer did not leak pre-send text into xterm' "menu UI proof must prove native text is not sent before Send"
    require "$MENU_UI_PROOF" 'ensure_plain_toolbar' "menu UI proof must start toolbar assertions from Start-visible plain state"
    require "$MENU_UI_PROOF" 'dump_has_button_text' "menu UI proof must distinguish toolbar buttons from dialog text and hints"
    require "$MENU_UI_PROOF" 'WEZTERM_UI_ALLOW_CLEAR_DRAFT' "menu UI proof must not silently clear an unsent native composer draft"
    require "$MENU_UI_PROOF" 'UIAutomator reports the hint as text' "menu UI proof must not mistake an empty composer hint for user draft text"
    require "$MENU_UI_PROOF" 'assert_composer_terminal_refit' "menu UI proof must prove keyboard/composer layout changes refit ttyd/xterm rows"
    require "$MENU_UI_PROOF" 'Zoomed/native composer terminal refit kept the true bottom viewport usable' "menu UI proof must prove the zoomed true-bottom/full-area fix"
    require "$MENU_UI_PROOF" 'Native composer delivered one visible token' "menu UI proof must prove native composer submit without duplicate input"
    require "$MENU_UI_PROOF" 'Tap-to-type did not trigger page-finished or scroll bursts' "menu UI proof must prove tap-to-type does not jump/refresh"
    require "$MENU_UI_PROOF" 'IME flags stayed normal for voice input' "menu UI proof must keep voice-friendly IME flags guarded"
    require "$MENU_UI_PROOF" 'Create bug report button created report' "menu UI proof must prove bug report button writes a report"
    require "$MENU_UI_PROOF" 'Install/update button launched external install surface' "menu UI proof must prove install button fires ACTION_VIEW"
    require "$MENU_UI_PROOF" 'wait_for_active_window_id "$proof_window"' "menu UI proof must reselect the disposable proof window after external install-page launch"
    require "$MENU_UI_PROOF" 'Copy/Paste buttons round-tripped full multi-word text' "menu UI proof must prove Copy and Paste through Android clipboard plus tmux with spaces"
    require "$MENU_UI_PROOF" 'Start button sent Enter' "menu UI proof must prove Start sends Enter"
    require "$MENU_UI_PROOF" 'Stop button delivered Escape' "menu UI proof must prove Stop sends Escape"
    require "$MENU_UI_PROOF" 'Close button removed disposable session' "menu UI proof must prove Close removes only the disposable session"
    require "$MENU_UI_PROOF" 'orig_mode' "menu UI proof must preserve original tmux mode"
    require "$MENU_UI_PROOF" 'orig_scroll' "menu UI proof must preserve original tmux scroll position"
    require "$MENU_UI_PROOF" 'old-session date header' "menu UI proof must verify old sessions are grouped by date"
    require "$MENU_UI_PROOF" 'assert_old_sessions_without_agent_labels' "menu UI proof must prove subagent/agent wording is absent from Old Sessions in one stable UI dump"
    require "$MENU_UI_PROOF" 'tap_text "Active"' "menu UI proof must open Active Sessions"
    require "$MENU_UI_PROOF" 'assert_text "Active Sessions"' "menu UI proof must verify Active Sessions"
    require "$MENU_UI_PROOF" 'long_press_text "Scroll"' "menu UI proof must open the command palette through long-press Scroll"
    require "$MENU_UI_PROOF" 'scroll_until_text()' "menu UI proof must scroll native command-palette dialogs before checking off-screen items"
    require "$MENU_UI_PROOF" 'tap_visible_text_from_current_dump' "menu UI proof must tap scrolled dialog items from the same visible dump"
    require "$MENU_UI_PROOF" 'swipe_first_scrollable_down' "menu UI proof must use UIAutomator scrollable bounds instead of hardcoded dialog coordinates"
    require "$MENU_UI_PROOF" 'assert_text "Needs Attention"' "menu UI proof must verify Needs Attention remains available"
    require "$MENU_UI_PROOF" 'assert_absent "Previous Sessions"' "menu UI proof must keep the confusing Previous Sessions label out"
    require "$MENU_UI_PROOF" 'tap_text "Copy/Paste"' "menu UI proof must open Copy/Paste"
    require "$MENU_UI_PROOF" 'assert_text "Upload media from phone"' "menu UI proof must verify the media upload control exists"
    require "$MENU_UI_PROOF" 'Phone menu UI button proof passed' "menu UI proof must have an explicit success marker"
else
    echo "Phone plan regression guard failed: scripts/prove-phone-menu-ui.sh is required" >&2
    exit 1
fi
require "$MAIN" 'toolbarButton("Active", v -> showActiveSessions())' "Active Sessions must remain on the main toolbar"
require "$MAIN" 'toolbarButton("Old", v -> showOldSessions())' "Old Sessions must remain on the main toolbar"
require "$MAIN" 'toolbarButton("New", v -> control("/new?fast=1", "New session opened"))' "New session must remain on the main toolbar"
require "$MAIN" 'toolbarButton("Refresh", v -> refreshTerminalTransport())' "Refresh must remain on the main toolbar"
require "$MAIN" 'toolbarButton("Bottom", v -> goLiveBottom())' "Bottom must remain a one-tap live-bottom toolbar button"
require "$MAIN" 'toolbarButton("Scroll", v -> showViewControls())' "Scroll recovery menu must remain visible"
require "$MAIN" 'toolbarButton("Copy/Paste", v -> showCopyPasteControls())' "Copy/Paste must remain visible"
require "$MAIN" 'toolbarButton("Upload", v -> pickMediaForUpload())' "direct media Upload must remain visible on the main toolbar"
require "$MAIN" 'private LinearLayout toolbarRow()' "toolbar must stay split into readable rows"
require "$MAIN" 'setTouchableBackground(button' "toolbar buttons must keep visible ripple/tap feedback"
require "$MAIN" 'flashTap(v)' "buttons and rows must visibly acknowledge taps"
require "$MAIN" 'toolbarButton("Close", v -> confirmClose())' "Close current session must remain visible"
require "$MAIN" 'toolbarButton("Start", v -> startCurrentTask())' "Start/send must remain visible"
require "$MAIN" 'toolbarButton("Stop", v -> stopCurrentTask())' "Stop/interrupt must remain visible"
require_absent "$MAIN" 'toolbarButton("Steer"' "Steer must not return; Start and Stop are separate"
require_absent "$MAIN" 'stopAndSteer' "old Steer method must not return"
require_absent "$MAIN" 'sendOrStop' "combined Send/Stop behavior must not return"
require_absent "$MAIN" 'toolbarButton("Tabs"' "Tabs must not return as the primary phone wording; use Active Sessions"
require_absent "$MAIN" 'toolbarButton("New Tab"' "New Tab must not return as the primary phone wording; use New"
require_absent "$MAIN" 'toolbarButton("Close Tab"' "Close Tab must not return as the primary phone wording; use Close"
require_absent "$MAIN" 'toolbarButton("Live"' "Live must not be reintroduced as a main toolbar button without a new proven plan receipt"
require_absent "$MAIN" 'toolbarButton("Read"' "Read must not replace the visible Scroll recovery entry"
require_absent "$MAIN" 'toolbarButton("View"' "View must not replace the visible Scroll recovery entry"

require "$MAIN" '"Go to live bottom / type"' "Scroll menu must keep live-bottom/type recovery"
require_absent "$MAIN" '"Command palette",' "Scroll menu must stay scroll-only; use long-press Scroll for the command palette"
require "$MAIN" 'scrollButton.setOnLongClickListener' "Scroll long-press must preserve command palette access without polluting the Scroll dialog"
require "$MAIN" 'private void showCommandPalette()' "command palette method must remain implemented"
require "$MAIN" '"Refresh current session"' "command palette must expose refresh"
require "$MAIN" '"Active Sessions"' "command palette must expose Active Sessions"
require "$MAIN" '"Old Sessions"' "command palette must expose Old Sessions"
require "$MAIN" '"Needs Attention"' "command palette must expose Needs Attention"
require_absent "$MAIN" '"Sessions by date"' "old ambiguous sessions-by-date label must not return"
require_absent "$MAIN" '"Previous Sessions"' "Previous Sessions label must not return; user asked for Old Sessions"
require_absent "$MAIN" '"Needs attention"' "Needs Attention capitalization must stay consistent"
require "$MAIN" '.setTitle("Scroll")' "Scroll button must open the small scroll-specific menu, not the old giant terminal controls list"
require_absent "$MAIN" '.setTitle("Terminal Controls")' "old giant Scroll/Terminal Controls menu must not return"
require_absent "$MAIN" '"Smaller terminal text"' "Scroll menu must not contain text-size controls"
require_absent "$MAIN" '"Larger terminal text"' "Scroll menu must not contain text-size controls"
require_absent "$MAIN" '"Current text size:' "Scroll menu must not contain status/info rows"
require "$MAIN" '"Create bug report"' "command palette must expose bug-report"
require "$MAIN" '"Install/update over Tailscale"' "command palette must expose no-USB install page"
require "$MAIN" '"Go to history top"' "Scroll menu must keep true-top recovery"
require "$MAIN" '"Read current session"' "Scroll menu must keep current-session reader"
require_absent "$MAIN" '"Open full session reader"' "old reader label must not return"
require "$MAIN" '"Page up"' "Scroll menu must keep page up"
require "$MAIN" '"Page down"' "Scroll menu must keep page down"
require "$MAIN" '"Stop current task"' "Scroll menu must keep stop fallback"
require "$MAIN" '"Type prompt safely"' "menus must expose the native safe prompt composer"
require "$MAIN" '"Start / send Enter"' "menus must expose the explicit Start/send route"
require "$MAIN" 'restoreLiveForTyping("At live bottom")' "live-bottom action must force the terminal back to typing"
require "$MAIN" 'getJsonWithRetry("/live-bottom"' "live-bottom/tap-to-type recovery must use the fast no-refresh endpoint"
require "$MAIN" 'showDockedPromptComposer("live-bottom")' "live-bottom recovery must reveal the native composer instead of direct xterm IME"
require "$MAIN" 'leaveReadModeForLiveInput(false)' "tap-to-type live-bottom recovery must not run the full viewport pin before server recovery"
require "$MAIN" 'hideHistoryTouchOverlayQuietly()' "tap-to-type live-bottom recovery must be able to hide the read overlay without viewport-pin JS"
require_absent "$MAIN" 'getJson("/scroll?where=bottom"' "normal live-bottom recovery must not use the heavy scroll proof endpoint"
require_absent "$MAIN" 'keepLiveInputVisibleSoon("live-bottom")' "normal live-bottom recovery must not run xterm scrollToBottom/scrollIntoView bursts"
require "$MAIN" '"/select-live?fast=1&windowId="' "tab selection must target stable windowId and auto-return to live typing"
require "$MAIN" 'sessionSwitchInFlight' "tab selection must guard against double-tap switch races"
require_absent "$MAIN" 'reloadTerminalTransportOnly("select-live")' "Active Sessions row taps must not reload WebView; that caused visible refresh/glitch and multi-tap switching"
require_absent "$MAIN" 'keepLiveInputVisibleSoon("select-live")' "Active Sessions row taps must not run xterm scrollToBottom/scrollIntoView visibility bursts"
require "$MAIN" 'let ttyd paint the selected' "Active Sessions no-reload WHY comment must stay"
require "$MAIN" 'getJsonWithRetry(path, payload ->' "Active Sessions switching must retry safe control connection drops"
require "$MAIN" 'titleText.setOnClickListener(openSessionClick)' "Active row title must switch sessions with one tap"
require "$MAIN" 'detailText.setOnClickListener(openSessionClick)' "Active row detail must switch sessions with one tap"
require "$MAIN" 'statusDot.setOnClickListener(openSessionClick)' "Active row status dot must switch sessions with one tap"
require "$MAIN" 'installPlainToolbarTapHandler(button)' "plain toolbar buttons must use the deterministic in-bounds tap handler"
require "$MAIN" 'Do not install this on Scroll' "toolbar tap WHY comment must preserve protected long-press buttons"
require "$MAIN" 'addSectionHeader(list, "Current", 1)' "Active Sessions must pin the current window at the top"
require "$MAIN" 'activeWindowFromPayload(payload)' "Active Sessions must derive the current row from the server payload"
require "$MAIN" 'sameWindow(window, skipWindow)' "Active Sessions must not duplicate the current row in grouped sections"
require "$MAIN" 'addActiveDialogActions(list, dialogRef)' "Active Sessions must keep New/Rename/Cancel inside the visible scroll content"
require "$MAIN" 'stock AlertDialog three-button footer can stack or disappear' "Active Sessions action-row WHY comment must preserve the footer-clipping fix"
require "$MAIN" '"/close?fast=1&windowId="' "close must target stable windowId"
require "$MAIN" 'getJsonWithRetry("/active"' "main Close must use retry-safe active phone session metadata"
require "$MAIN" 'getJsonWithRetry("/sessions"' "Active/Old session pickers must use the retry-safe session/date endpoint"
require "$MAIN" 'getJsonWithRetry("/needs-attention"' "Needs Attention must use the retry-safe server endpoint"
require "$MAIN" 'payload.optString("viewSession"' "sessions UI must read phone view-session metadata"
require "$MAIN" 'activityGroup' "sessions UI must show date grouping metadata"
require "$MAIN" 'payload.optJSONArray("oldSessions")' "Old Sessions UI must render server oldSessions"
require "$MAIN" 'private void showOldSessionsDialog(JSONObject payload)' "Old Sessions dialog must remain implemented"
require "$MAIN" 'private int countOldSessionsForDate' "Old Sessions must group parent sessions by date"
require "$MAIN" 'private void confirmResumeOldSession' "Old Sessions must have a resume action"
require "$MAIN" '"/resume-session?fast=1&sessionId="' "Old Sessions must call the safe resume endpoint"
require "$MAIN" '!"user".equals(session.optString("threadSource", "user"))' "Old Sessions UI must filter non-user/subagent sessions"
require "$MAIN" 'Resume button is the action' "Old Sessions WHY comment must preserve date/name-only UI"
require "$MAIN" 'titleText.setSingleLine(false)' "session picker titles must wrap instead of truncating"
require "$MAIN" 'titleText.setMaxLines(Integer.MAX_VALUE)' "session picker titles must allow full title height"
require "$MAIN" 'titleText.setEllipsize(null)' "session picker titles must not ellipsize the title"
require "$MAIN" 'LinearLayout.LayoutParams.WRAP_CONTENT' "session picker rows must be allowed to grow with wrapped titles"
require "$MAIN" 'ClipData.newPlainText("WEzterm session title", title)' "full session title must be copyable from the phone"

require "$MAIN" 'ClipboardManager' "Copy/Paste must use Android clipboard APIs"
require "$MAIN" '"Paste phone clipboard into terminal"' "paste dialog option must remain"
require "$MAIN" '"Copy visible terminal text"' "copy dialog option must remain"
require "$MAIN" '"Upload media from phone"' "Copy/Paste menu must expose phone media upload"
require "$MAIN" 'copyPasteButton.setOnLongClickListener' "Copy/Paste long-press must keep a fast direct upload fallback"
require "$MAIN" 'showSafePromptComposer' "native prompt composer must remain available"
require "$MAIN" 'promptComposerInput = new EditText(this)' "docked native composer must remain implemented"
require "$MAIN" 'promptComposerInput.setContentDescription("Type prompt")' "native composer must be visible to UIAutomator proof"
require "$MAIN" 'showDockedPromptComposer("tap-up")' "normal terminal-body taps must open the native composer"
require "$MAIN" 'startToolbarButton.setText(promptComposerBar.getVisibility() == View.VISIBLE ? "Send" : "Start")' "existing Start button must become Send while the native composer is open"
require "$MAIN" 'KEYCODE_BACK && isDockedPromptComposerVisible()' "native composer must dismiss with Android Back instead of adding duplicate buttons"
require_absent "$MAIN" 'Button send = button("Send"' "native composer must not add a second Send button below the toolbar"
require_absent "$MAIN" 'Button cancel = button("Cancel"' "native composer must not add a hidden-looking Cancel button below the toolbar"
require "$MAIN" 'postText("/submit-text"' "safe prompt composer must send one server-side paste+Enter"
require "$MAIN" '"/send-enter"' "Start must use the server Enter route"
require "$MAIN" 'Intent.ACTION_OPEN_DOCUMENT' "phone media upload must use Android's user-selected document picker"
require "$MAIN" 'Intent.ACTION_SEND' "phone media upload must handle Android share intents"
require "$MAIN" 'REQUEST_UPLOAD_MEDIA' "phone media picker result must remain wired"
require "$MAIN" 'MAX_MEDIA_UPLOAD_BYTES' "phone media upload must keep a file-size guard"
require "$MAIN" '2L * 1024L * 1024L * 1024L' "phone media upload must allow large video-sized files"
require "$MAIN" 'setFixedLengthStreamingMode(declaredSize)' "known-size media uploads must stream without buffering in Android heap"
require "$MAIN" 'setChunkedStreamingMode(MEDIA_UPLOAD_STREAM_CHUNK_BYTES)' "unknown-size media uploads must use chunked streaming instead of buffering"
require "$MAIN" 'streamUriToOutput' "Android media upload must stream from ContentResolver to HTTP output"
require_absent "$MAIN" 'readUriBytes' "Android media upload must not read whole videos into a byte array"
require "$MAIN" '"/upload-media?filename="' "phone media upload must post to the control server upload endpoint"
require "$MAIN" 'postText("/paste"' "paste must go through the control-server paste endpoint"
require "$MAIN" 'clipboardTextFromClip(clip)' "paste must read the full Android ClipData, not just one truncated item"
require "$MAIN" 'for (int index = 0; index < clip.getItemCount(); index++)' "paste must join all text clip items"
require "$MAIN" 'item.getText()' "paste must prefer raw text before coercion"
require "$MAIN" 'item.coerceToText(this)' "paste must use Android's documented clipboard text coercion fallback"
require "$MAIN" 'getJson("/copy-visible"' "copy must go through the control-server copy endpoint"

require "$MAIN" 'VelocityTracker' "slow-vs-fast flick behavior must keep Android velocity tracking"
require "$MAIN" 'HISTORY_DRAG_THROTTLE_MS = 16' "touch scroll must stay responsive enough to track a finger"
require "$MAIN" 'HISTORY_DRAG_LINE_THRESHOLD_DP = 8' "touch scroll must use line-sized movement threshold"
require "$MAIN" 'HISTORY_DRAG_PAGES_PER_STEP = 1' "slow scroll must stay controlled"
require "$MAIN" 'HISTORY_DRAG_MAX_PAGES_PER_STEP = 20' "fast flick must stay capped at the server-supported touch burst"
require "$MAIN" 'HISTORY_DRAG_DOWN_MAX_REPEATS = 20' "downward scroll batches must be fast enough to return to live without stalling"
require "$MAIN" 'HISTORY_DRAG_DOWN_RELEASE_MAX_REPEATS = 20' "downward release flings must match the server-supported touch batch"
require "$MAIN" 'TOUCH_SCROLL_LIVE_BOTTOM_SNAP_LINES = 16' "near-bottom lineDown must quietly restore live bottom"
require "$MAIN" 'HISTORY_DRAG_FLING_VELOCITY_PX_PER_SEC' "fast flick threshold must remain explicit"
require "$MAIN" 'terminalTouchGestureGeneration' "touch scrolling must generation-cancel stale delayed responses"
require "$MAIN" 'pendingHistoryScrollGeneration' "pending touch scrolls must belong to the current gesture"
require "$MAIN" 'sendHistoryScrollFromTouch(where, boundedRepeats, gestureGeneration)' "touch scrolling must batch through bounded generation-tagged server repeats"
require "$MAIN" 'String where = step > 0 ? "lineUp" : "lineDown"' "touch scroll must use line-sized server movement, not page jumps"
require "$MAIN" 'scrollTerminalFromTouch(where, repeats)' "touch scroll must dispatch the explicit line-sized direction"
require "$MAIN" 'dispatchHistoryReleaseFling(event)' "fast flick must add a bounded ACTION_UP burst so it moves farther than slow drag"
require "$MAIN" 'one bounded release burst' "release-fling WHY comment must remain"
require "$MAIN" 'HISTORY_DRAG_RELEASE_FLING_BURSTS = 2' "full fling must keep the delayed second burst"
require "$MAIN" 'A second short-delay burst gives real fling velocity' "delayed fling-burst WHY comment must remain"
require "$MAIN" 'flingGeneration == terminalTouchGestureGeneration' "delayed fling burst must be cancelled by a newer pinch/gesture"
require "$MAIN" '!terminalMultiTouchGesture' "delayed fling burst must not run during/after pinch zoom"
require "$MAIN" 'single-burst' "downward flings must stay single-burst and not queue the delayed second burst"
require "$MAIN" 'stall in copy-mode many' "downward return WHY comment must preserve the physical proof failure"
require "$MAIN" 'server-supported touch batch' "downward return WHY comment must preserve the control-server cap reason"
require "$MAIN" 'gestureGeneration != terminalTouchGestureGeneration' "stale touch-scroll replies must be ignored"
require "$MAIN" 'terminalTouchReachedLiveBottom' "touch scroll must remember the live-bottom edge during a drag"
require "$MAIN" 'touchScrollReachedLiveBottom' "touch scroll responses must exit read mode at the live bottom"
require "$MAIN" '"tmux-linedown".equals(payload.optString("action", ""))' "live-bottom detection must be restricted to tmux lineDown touch responses"
require "$MAIN" 'isNearTmuxLiveBottom(payload)' "near-bottom restore must use server-reported tmux scrollPosition"
require "$MAIN" 'payload.has("scrollPosition")' "near-bottom restore must require explicit server scrollPosition data"
require "$MAIN" 'restoreTouchLiveBottomQuietly();' "near-bottom lineDown after finger-up must use the quiet bottom restore path"
require "$MAIN" 'extra downward' "live-bottom edge WHY comment must prevent down-scroll bounce regressions"
require "$MAIN" '"/touch-scroll?where="' "one-finger touch scroll must use the lightweight tmux-only endpoint"
require "$MAIN" 'restoreTouchLiveBottomQuietly()' "finger-up at live bottom must quietly exit tmux copy-mode"
require "$MAIN" '"/touch-scroll?where=bottom&repeat=1"' "finger-up bottom restore must use lightweight touch-scroll, not the heavy /scroll endpoint"
require "$MAIN" 'hideHistoryTouchOverlayQuietly()' "quiet bottom restore must hide the overlay without running full live-input focus"
require "$MAIN" 'skip WebView reload, xterm' "quiet bottom WHY comment must preserve the no-refresh/no-scrollIntoView reason"
require "$MAIN" 'terminalBottomRestoreInFlight' "gesture recovery must block delayed reload/focus probes at the bottom edge"
require "$MAIN" 'isTerminalGestureRecoveryActive()' "focus/reconnect/blank watchdog paths must share the gesture-recovery gate"
require_absent "$MAIN" 'restoreTouchLiveBottom()' "old heavy finger-up bottom restore method must not return"
require_absent "$MAIN" '+ "&mode=touch&repeat="' "one-finger MOVE must not return to the heavy /scroll endpoint"
require "$MAIN" 'showHistoryTouchOverlay()' "history/read mode overlay must keep swipes deterministic"
require "$MAIN" 'hideHistoryTouchOverlay()' "live typing must hide the history overlay"

require "$MAIN" 'pinTerminalViewportSoon' "old-tab viewport pin must remain"
require "$MAIN" 'document.scrollingElement' "WebView document scrolling must be pinned"
require "$MAIN" 'window.scrollTo(0,0)' "WebView viewport must be reset to the top-left"
require "$MAIN" 'view.setScrollContainer(false)' "WebView must not become the terminal scroll container"
require "$MAIN" 'view.setOverScrollMode(View.OVER_SCROLL_NEVER)' "WebView overscroll refresh effect must stay disabled"
require "$MAIN" 'WEBVIEW_ZOOMED_SCALE_THRESHOLD' "WebView zoom state must remain explicit"
require "$MAIN" 'private boolean isViewerPanAllowed()' "zoomed WebView panning must not be pinned away"
require "$MAIN" 'allowViewerPanBriefly()' "two-finger and horizontal viewer pan must unlock the WebView viewport"
require "$MAIN" 'terminalViewerDownEvent = MotionEvent.obtain(event)' "consumed ACTION_DOWN must be replayable when gesture becomes WebView-owned"
require "$MAIN" 'return forwardTouchToViewer(event);' "pinch/horizontal gestures must be explicitly forwarded to WebView"
require "$MAIN" 'forwardTapToViewer(event)' "top tmux/status taps must still reach ttyd/xterm after the tmux-owned DOWN classification"
require "$MAIN" 'isTopTerminalTap(event)' "only the top tmux/status strip should receive forwarded single-finger tap events"
require "$MAIN" 'terminal body taps open the native composer' "terminal body tap WHY comment must preserve native composer ownership"
require "$MAIN" 'public void onScaleChanged(WebView view, float oldScale, float newScale)' "Android/WebView zoom changes must be tracked"
require "$MAIN" 'Do not translate this' "WebView zoom must not be converted into tmux/font resize behavior"
require "$MAIN" 'fitTerminalToCurrentViewSoon("webview-layout")' "Android layout changes must refit ttyd/xterm without a WebView reload"
require "$MAIN" 'window.dispatchEvent(new Event('"'"'resize'"'"'))' "xterm/ttyd must be told about Android WebView layout changes"
require "$MAIN" 't.refresh(0,Math.max(0,t.rows-1))' "xterm canvas redraw must stay guarded for dotted/full-area repaint"
require "$MAIN" 'scrollViewerToTypingPositionSoon("touch-bottom")' "one-finger live-bottom restore must move the zoomed Android viewer to true bottom"
require "$MAIN" 'without reviving xterm' "zoomed bottom WHY comment must preserve the no-refresh/no-duplicate-typing constraint"

require "$MAIN" 'terminalFocusAndReconnectProbeScript' "focus path must keep narrow reconnect overlay detection"
require "$MAIN" 'Press ↵ to Reconnect' "exact observed reconnect overlay must stay documented"
require "$MAIN" 'needsReconnect:overlay' "reconnect probe must return a machine-readable reconnect decision"
require "$MAIN" 'reloadTerminalForReconnect();' "detected reconnect overlay must auto-reload"
require "$MAIN" 'Pressing Enter here would send a real key' "synthetic Enter must remain forbidden"
require "$MAIN" 'TERMINAL_FOCUS_BURST_MIN_INTERVAL_MS' "focus retries must remain burst-collapsed"
require "$MAIN" 'terminalFocusGeneration' "stale focus callbacks must remain generation-cancelled"
require "$MAIN" 'generation != terminalFocusGeneration' "stale terminal focus callbacks must not run after newer focus"
require "$MAIN" 'LIVE_INPUT_VISIBILITY_BURST_MIN_INTERVAL_MS' "live-input visibility retries must remain burst-collapsed"
require "$MAIN" 'liveInputVisibilityGeneration' "stale live-input visibility callbacks must remain generation-cancelled"
require "$MAIN" 'native composer is the default phone typing surface' "native composer WHY comment must preserve the duplicate typing fix"
require "$MAIN" '!requestKeyboard' "passive focus retries must not also be keyboard retries"
require "$MAIN" 'postTerminalFocusRetry(generation, false, 180)' "passive lifecycle focus can keep one reconnect-only retry"
require "$MAIN" '"no-input".equals(probeStatus)' "keyboard retry must be conditional on the xterm textarea being absent"
require "$MAIN" 'postTerminalFocusRetry(generation, true, 180)' "tap-to-type may retry only when the first probe finds no textarea"
require "$MAIN" 'recommit the same composing text' "tap-to-type WHY comment must preserve the duplicate text root cause"
require_absent "$MAIN" 'focusTerminalInputSoon(true)' "normal phone actions must not reopen direct xterm WebView IME"
require_absent "$MAIN" 'showSoftInput(webView' "WebView/xterm must not own Android IME typing in v1.67"
require_absent "$MAIN" 'showKeyboardIfLive' "old direct WebView IME show helper must not return"
require_absent "$MAIN" 'scheduleLiveTapFocus' "terminal body taps must not use the old delayed xterm focus scheduler"
require_absent "$MAIN" 'postTerminalFocusRetry(generation, requestKeyboard, 180)' "unconditional keyboard focus retry must not return"
require_absent "$MAIN" 'postTerminalFocusRetry(generation, true, 600)' "old 600 ms keyboard retry must not return"
require_absent "$MAIN" 'postTerminalFocusRetry(generation, true, 950)' "old 950 ms keyboard retry must not return"
require "$MAIN" 'requestKeyboard && !webView.hasFocus()' "native WebView focus must not restart when it is already focused"
require "$MAIN" 'SOFT_INPUT_ADJUST_RESIZE' "keyboard layout must still resize the terminal surface"
require_absent "$MAIN" 'SOFT_INPUT_STATE_VISIBLE' "activity-level keyboard forcing must not return"
require "$MAIN" 'keyboardVisibleForFocusedWebView()' "passive WebView focus probes must still know when an IME is already visible"
require "$MAIN" 'generic toolbar/control actions are asynchronous' "late generic control focus WHY comment must stay"
require "$MAIN" 'readModeGeneration == terminalModeGeneration' "generic async controls must verify the mode generation before refocusing"
require "$MAIN" 'touchGeneration == terminalTouchGestureGeneration' "generic async controls must verify no newer terminal tap started typing"
require "$MAIN" 'normal live taps advance only the touch generation' "late generic control WHY comment must preserve the touch-generation reason"
require "$MAIN" 'liveInputVisibilityGeneration++' "native composer and transport reloads must cancel stale scroll-to-bottom visibility retries"
require "$MAIN" 'showDockedPromptComposer("tap-up")' "terminal-body tap must open the native composer instead of delayed WebView IME focus"
require "$MAIN" 'same composed word can be committed twice' "native composer WHY comment must preserve the xterm/Android duplicate root cause"
require "$MAIN" 'document.activeElement!==el' "xterm textarea focus must be a no-op when already active"
require "$MAIN" 'focus({preventScroll:true})' "xterm textarea focus must avoid WebView scroll jumps"
require_absent "$MAIN" 'keepLiveInputVisibleSoon("focus")' "plain tap/focus must not scroll xterm to bottom or snap the composer to the top"
require_absent "$MAIN" 'keepLiveInputVisibleSoon("focus-collapsed")' "collapsed focus retries must not trigger xterm scroll-to-bottom"
require_absent "$MAIN" 'keepLiveInputVisibleSoon("page-finished")' "page-finished must not run scroll/visibility bursts"
require_absent "$MAIN" 'keepLiveInputVisibleSoon("safe-prompt")' "native prompt submit must not run xterm scroll/visibility bursts"
require_absent "$MAIN" 'keepLiveInputVisibleSoon("paste")' "paste must not run xterm scroll/visibility bursts after server-side paste"
require_absent "$MAIN" 'scheduleBlankTerminalWatchdog("page-finished")' "page-finished must not arm reload loops"
require "$MAIN" 'nativePickerQuietUntilMs' "Android document picker returns must suppress blank-watchdog reload loops"
require "$MAIN" 'TERMINAL_INPUT_TYPE' "terminal IME flags must stay centralized for voice-input regression review"
require "$MAIN" 'TYPE_TEXT_VARIATION_NORMAL' "terminal IME must advertise normal visible text so voice dictation remains available"
require_absent "$MAIN" 'TYPE_TEXT_VARIATION_VISIBLE_PASSWORD' "terminal IME must not look like password/private input; it hid phone voice dictation"
require_absent "$MAIN" 'TYPE_TEXT_FLAG_NO_SUGGESTIONS' "terminal IME must not globally suppress keyboard features; safe prompt paste handles long prompts"
require "$MAIN" 'IME_ACTION_SEND' "terminal IME action must advertise send"
require_absent "$MAIN" 'IME_FLAG_NO_PERSONALIZED_LEARNING' "terminal IME must not trigger private/incognito keyboard mode"
require "$MAIN" 'IME_FLAG_NO_FULLSCREEN' "terminal IME must avoid fullscreen extract UI"
require "$MAIN" 'markTerminalLoadStarted()' "every WebView reload must invalidate stale focus/watchdog callbacks"
require "$MAIN" 'terminalFocusGeneration++' "WebView reloads must cancel stale focus callbacks"
require "$MAIN" 'liveInputVisibilityGeneration++' "WebView reloads must cancel stale visibility callbacks"
require "$MAIN" 'lastTerminalLoadAtMs = now' "blank-terminal watchdog must use explicit load generations"
require_absent "$MAIN" 'el.click()' "hidden xterm textarea click must not return; it duplicated input before"
require_absent "$MAIN" 'uiHandler.postDelayed(() -> focusTerminalInput(), 2400)' "old 2.4s unguarded focus retry must not return"

require "$MAIN" 'settings.setSupportZoom(true)' "pinch/zoom support must stay enabled"
require "$MAIN" 'settings.setBuiltInZoomControls(true)' "built-in WebView zoom must stay enabled"
require "$MAIN" 'settings.setDisplayZoomControls(false)' "old visible zoom controls must stay hidden"
require "$MAIN" 'WindowInsets.Type.ime()' "IME inset must be considered"
require "$MAIN" 'bottom = bars.bottom' "toolbar height must not include keyboard IME height"
require "$MAIN" 'keyboardReserve = Math.max(0, ime.bottom - bars.bottom)' "root layout must reserve keyboard space outside the toolbar"
require "$MAIN" 'never add it to the toolbar height itself' "toolbar inset WHY comment must preserve the no-giant-toolbar rule"
require "$MAIN" 'IME is not part of the toolbar' "toolbar inset WHY comment must prevent giant bottom bar regressions"
require "$MAIN" 'keepLiveInputVisibleSoon' "live typing must keep the xterm input visible above the keyboard"
require "$MAIN" 'scrollViewerToTypingPosition' "zoomed WebView must move down to the live input above the IME"
require "$MAIN" 'VIEWER_PAN_UNLOCK_MS = 2500' "two-finger pan must keep a long enough native viewer ownership window"
require "$MAIN" 'A 900 ms unlock' "two-finger pan WHY comment must preserve the old snap-back failure"
require_absent "$MAIN" 'Smaller text / zoom out' "terminal text-size controls must not masquerade as Android viewer zoom"
require_absent "$MAIN" 'Larger text / zoom in' "terminal text-size controls must not masquerade as Android viewer zoom"
require "$MAIN" 'private void refreshTerminalTransport()' "Refresh implementation must remain"
require "$MAIN" 'getJsonWithRetry("/fix-view"' "Refresh must retry the server preserve/fix active tmux view call"
require "$MAIN" 'webView.loadUrl(currentUrl == null ? TERMINAL_URL : currentUrl)' "Refresh must reload only the WebView transport"
require "$MAIN" 'pinTerminalViewportSoon(reason)' "Refresh must repin WebView viewport"
require "$MAIN" 'scheduleBlankTerminalWatchdog(reason)' "Refresh must reuse blank-terminal watchdog"
require "$MAIN" 'private void openInstallPage()' "no-USB install page opener must remain"
require "$MAIN" 'new Intent(Intent.ACTION_VIEW, Uri.parse(INSTALL_URL))' "install page must open through Android ACTION_VIEW"
require "$MAIN" 'private void createBugReport()' "bug-report UI must remain implemented"
require "$MAIN" 'postText("/bug-report"' "bug-report UI must call the server endpoint"

if [ -f "$CONTROL_SERVER" ]; then
    require "$CONTROL_SERVER" 'parser.add_argument("--view-session", default="main_phone")' "control server must default to the phone view session"
    require "$CONTROL_SERVER" 'target = f"{self.active_target_session()}:{stable_id}"' "select must qualify stable windowId in the phone view"
    require "$CONTROL_SERVER" 'DEFAULT_NEW_SESSION_CWD' "server must have an explicit new-session cwd"
    require "$CONTROL_SERVER" 'PHONE_NEW_SESSION_CWD' "new-session cwd override must be explicit"
    require "$CONTROL_SERVER" '"-c",' "tmux new-window must use an explicit start directory"
    require "$CONTROL_SERVER" 'cd " + shlex.quote(DEFAULT_NEW_SESSION_CWD)' "new sessions must cd into the desktop user root"
    require "$CONTROL_SERVER" 'def select_live(self, index=None, window_id=None):' "server must implement fast select+live restore"
    require "$CONTROL_SERVER" 'def live_bottom_fast(self):' "server must implement a lightweight live-bottom helper for switch/send/paste"
    require "$CONTROL_SERVER" 'latency-sensitive live-input operations' "live-bottom fast path WHY comment must preserve the latency reason"
    require "$CONTROL_SERVER" 'elif parsed.path == "/live-bottom":' "GET /live-bottom route must expose the fast no-refresh live-bottom helper"
    require "$CONTROL_SERVER" 'elif parsed.path == "/select-live":' "GET /select-live route must remain"
    require "$CONTROL_SERVER" 'run_tmux("kill-window", "-t", target)' "close must kill the tmux window/process"
    require "$CONTROL_SERVER" 'repeat = max(1, min(repeat, 20))' "server scroll repeats must be capped"
    require "$CONTROL_SERVER" 'where in {"lineup", "upone"}' "server must preserve line-up touch scrolling"
    require "$CONTROL_SERVER" 'where in {"linedown", "downone"}' "server must preserve line-down touch scrolling"
    require "$CONTROL_SERVER" '"scroll-up"' "tmux touch scroll must use real copy-mode line scrolling"
    require "$CONTROL_SERVER" '"scroll-down"' "tmux touch scroll must use real copy-mode line scrolling"
    require "$CONTROL_SERVER" 'phone_touch_scroll = (request_mode or "").strip().lower() == "touch"' "one-finger phone touch scroll must bypass Codex transcript routing"
    require "$CONTROL_SERVER" 'def touch_scroll(self, where, repeat=1):' "server must implement the lightweight touch-scroll endpoint"
    require "$CONTROL_SERVER" 'elif parsed.path == "/touch-scroll":' "GET /touch-scroll route must remain"
    require "$CONTROL_SERVER" 'skip Codex/reader' "touch-scroll WHY comment must preserve the low-latency reason"
    require "$CONTROL_SERVER" '"atLiveBottom"] = True' "server must expose the tmux live-bottom edge to Android touch scroll"
    require "$CONTROL_SERVER" 'pane_in_copy_mode = run_tmux("display-message", "-p", "-t", target, "#{pane_in_mode}").strip() == "1"' "bottom after tmux touch-scroll must exit tmux copy-mode before Codex transcript routing"
    require "$CONTROL_SERVER" 'a desktop mouse wheel in tmux copy-mode' "touch-scroll intent comment must prevent Codex-history regressions"
    require "$CONTROL_SERVER" '"codexNoAltScreen"' "scroll layer must keep no-alt-screen Codex routing evidence"
    require "$CONTROL_SERVER" 'def codex_thread_id_from_open_files' "reader must infer npm-managed Codex thread IDs from open session files"
    require "$CONTROL_SERVER" 'def codex_thread_id_from_open_file_tree' "reader must walk from npm wrapper to native Codex process"
    require "$CONTROL_SERVER" '/.codex/sessions/' "reader open-file fallback must only inspect Codex session JSONL paths"
    require "$CONTROL_SERVER" 'payload.get("source") == "cli"' "reader open-file fallback must reject subagent source payloads"
    require "$CONTROL_SERVER" '"activityAt": activity_at' "tabs must expose activity ordering data"
    require "$CONTROL_SERVER" '"activityGroup": activity_group(activity_at)' "tabs must expose date grouping data"
    require "$CONTROL_SERVER" '"statusLabel": status["label"]' "tabs must expose running/done status labels"
    require "$CONTROL_SERVER" '"needsAttention": status["needsAttention"]' "tabs must expose needs-attention data"
    require "$CONTROL_SERVER" 'def recent_codex_sessions_from_state_db(limit):' "server must read old Codex session names from Codex state DB"
    require "$CONTROL_SERVER" "source = 'cli'" "old sessions must be limited to normal CLI sessions"
    require "$CONTROL_SERVER" "COALESCE(thread_source, 'user') = 'user'" "old sessions must exclude subagent threads"
    require "$CONTROL_SERVER" "COALESCE(agent_nickname, '') = ''" "old sessions must exclude named subagents"
    require "$CONTROL_SERVER" 'payload.get("agent_nickname")' "old-session JSONL fallback must also exclude named subagents"
    require "$CONTROL_SERVER" '"dateLabel": date_label_from_timestamp' "old sessions must expose exact date labels"
    require "$CONTROL_SERVER" 'payload["oldSessions"] = old_sessions' "server must expose explicit oldSessions payload"
    require "$CONTROL_SERVER" 'payload["recentCodexSessions"] = old_sessions' "server must keep recentCodexSessions compatibility alias"
    require "$CONTROL_SERVER" 'def resume_session(self, session_id, cwd="", include_tabs=True, dry_run=False):' "server must implement safe old-session resume"
    require "$CONTROL_SERVER" '"action": "resume-dry-run"' "server must support safe resume dry-run proof"
    require "$CONTROL_SERVER" 'exec codex --no-alt-screen resume' "old-session resume must use no-alt-screen Codex resume"
    require "$CONTROL_SERVER" 'elif parsed.path == "/resume-session":' "GET /resume-session route must remain"
    require "$CONTROL_SERVER" 'def sessions(self):' "server sessions endpoint must remain implemented"
    require "$CONTROL_SERVER" 'def needs_attention(self):' "server needs-attention endpoint must remain implemented"
    require "$CONTROL_SERVER" 'def fix_view(self):' "server fix-view endpoint must remain implemented"
    require "$CONTROL_SERVER" 'def bug_report(self, body=""):' "server bug-report endpoint must remain implemented"
    require "$CONTROL_SERVER" 'elif parsed.path == "/sessions":' "GET /sessions route must remain"
    require "$CONTROL_SERVER" 'elif parsed.path == "/needs-attention":' "GET /needs-attention route must remain"
    require "$CONTROL_SERVER" 'elif parsed.path == "/fix-view":' "GET /fix-view route must remain"
    require "$CONTROL_SERVER" 'elif parsed.path == "/bug-report":' "bug-report route must remain"
    require "$CONTROL_SERVER" 'def paste_text(self, text):' "server paste endpoint must remain implemented"
    require "$CONTROL_SERVER" 'load-buffer", "-b", "phone-paste", "-"' "paste must load tmux buffer from stdin"
    require "$CONTROL_SERVER" 'paste-buffer", "-d", "-p", "-b", "phone-paste"' "paste must use tmux paste-buffer"
    require "$CONTROL_SERVER" 'def copy_visible(self):' "server copy-visible endpoint must remain implemented"
    require "$CONTROL_SERVER" 'MAX_UPLOAD_BYTES' "server media uploads must keep a size cap"
    require "$CONTROL_SERVER" '2 * 1024 * 1024 * 1024' "server media upload cap must allow video-sized files"
    require "$CONTROL_SERVER" 'UPLOAD_READ_CHUNK_BYTES' "server media uploads must stream to disk in bounded chunks"
    require "$CONTROL_SERVER" 'def safe_upload_filename' "server media upload filenames must be sanitized"
    require "$CONTROL_SERVER" 'def upload_media_stream(self, filename, content_type, stream, length=None, chunked=False):' "server media upload endpoint must stream request bodies"
    require "$CONTROL_SERVER" 'def _copy_chunked_upload_to_file' "server must accept chunked streaming uploads from Android unknown-size media"
    require "$CONTROL_SERVER" 'Transfer-Encoding' "server upload route must detect chunked transfer encoding"
    require "$CONTROL_SERVER" '~/phone-uploads' "server media upload must save to the desktop phone-uploads folder"
    require "$CONTROL_SERVER" 'elif parsed.path == "/copy-visible":' "GET /copy-visible route must remain"
    require "$CONTROL_SERVER" 'parsed.path == "/upload-media"' "POST /upload-media route must remain"
    require "$CONTROL_SERVER" 'if parsed.path == "/paste":' "POST /paste route must remain"
    require "$CONTROL_SERVER" 'def send_enter(self):' "server send-enter endpoint must remain implemented"
    require "$CONTROL_SERVER" 'elif parsed.path == "/send-enter":' "GET /send-enter route must remain"
    require "$CONTROL_SERVER" 'def submit_text(self, text):' "server submit-text endpoint must remain implemented"
    require "$CONTROL_SERVER" 'elif parsed.path == "/submit-text":' "POST /submit-text route must remain"
    require "$CONTROL_SERVER" 'def stop(self):' "server stop endpoint must remain implemented"
    require "$CONTROL_SERVER" '"keys": ["Escape", "Escape"]' "Stop must send the protected double-Escape interrupt"
fi

if [ -f "$PHONE_TERMINAL" ]; then
    require "$PHONE_TERMINAL" 'PHONE_TITLE_SYNC_ENABLED:-1' "title sync should remain enabled by default"
    require "$PHONE_TERMINAL" 'scrollback=$PHONE_SCROLLBACK' "ttyd scrollback must use the configurable large cap"
    require "$PHONE_TERMINAL" '--client-option rendererType=canvas' "ttyd must keep canvas renderer"
    require "$PHONE_TERMINAL" '--client-option scrollOnUserInput=true' "ttyd must keep scroll-on-input behavior"
fi

if [ -f "$PHONE_ADB_CONNECT" ]; then
    require "$PHONE_ADB_CONNECT" 'Tailscale relay is online: ${RELAY_HOST}:${RELAY_PORT} -> ${PHONE_TAILSCALE_IP}:5555' "no-USB Tailscale relay proof path must remain"
    require "$PHONE_ADB_CONNECT" 'phone-adb-connect install [ADB_SERIAL] [APK_PATH]' "no-USB install helper must remain documented"
    require "$PHONE_ADB_CONNECT" 'install_apk()' "no-USB install helper must remain implemented"
    require "$PHONE_ADB_CONNECT" '127.0.0.1' "relay must keep localhost ADB target"
    require "$PHONE_ADB_CONNECT" 'PHONE_TAILSCALE_IP' "relay must remain Tailscale-backed"
fi

require "$ROOT/build-apk.sh" 'sha256sum build/WEzterm.apk' "build must derive the install page checksum from the signed APK"
require "$ROOT/build-apk.sh" 'cat > build/install.html' "build must regenerate the public install page after signing"
require "$ROOT/build-apk.sh" 'WEzterm v${VERSION_NAME}' "build-generated install page must use the manifest version"

require "$ROOT/scripts/prove-phone-runtime-regression.sh" 'old session JSONL fallback filter' "runtime proof must force the old-session JSONL fallback filter"
require "$ROOT/scripts/prove-phone-runtime-regression.sh" 'touch top reaches tmux history top' "runtime proof must keep true-top tmux scroll coverage"
require "$ROOT/scripts/prove-phone-menu-ui.sh" 'Read current session opened reader' "UI proof must exercise the reader button"
require "$ROOT/scripts/prove-phone-menu-ui.sh" 'reader_source_window="$(tmux_active_window)"' "UI proof must bind reader assertions to the selected source window"
require "$ROOT/scripts/prove-phone-menu-ui.sh" 'reader window did not name its selected source' "UI proof must diagnose reader/source mismatches without stale orig_window assumptions"
require "$ROOT/scripts/prove-phone-menu-ui.sh" 'scroll_until_text "$PROOF_NAME"' "UI proof must scroll crowded Active Sessions before tapping the disposable proof title"
require "$ROOT/scripts/prove-phone-menu-ui.sh" 'dump_has_button_text "Scroll"' "UI proof must verify the real Scroll toolbar button before tapping it from a cached dump"
require "$ROOT/scripts/prove-phone-menu-ui.sh" 'Physical one-finger slow/fast scroll proved' "UI proof must exercise physical slow-vs-fast swipe behavior"
require "$ROOT/scripts/prove-phone-menu-ui.sh" 'assert_terminal_toolbar_geometry' "UI proof must fail when toolbar consumes the terminal bottom"
require "$ROOT/scripts/prove-phone-menu-ui.sh" 'toolbar is consuming hidden-keyboard space' "UI proof must catch the giant blank toolbar regression"
require "$ROOT/scripts/prove-phone-menu-ui.sh" 'terminal screenshot text pixels' "UI proof must pixel-check Refresh repaint"
require "$ROOT/scripts/prove-phone-menu-ui.sh" 'Native composer delivered one visible token' "UI proof must exercise native composer submit without duplicate input"
require "$ROOT/scripts/prove-phone-menu-ui.sh" 'Zoomed/native composer terminal refit kept the true bottom viewport usable' "UI proof must exercise the zoomed/full-area bottom refit"
require "$ROOT/scripts/prove-phone-menu-ui.sh" 'grep -Fo "$TYPE_TOKEN"' "UI proof must count duplicate tokens on the same line"
require "$ROOT/scripts/prove-phone-menu-ui.sh" 'could not capture a fresh $PACKAGE UI dump' "UI proof must diagnose stale UIAutomator dumps"
require "$ROOT/scripts/prove-phone-menu-ui.sh" 'tmux_window_pane_mode "$proof_window"' "UI proof must read the explicit proof window during physical scroll"

# WHY: Bash `-n` cannot parse embedded heredoc Python. The toolbar geometry
# proof is the guard that catches hidden composer rows and giant keyboard blanks;
# if its Python has bad indentation, the proof harness fails before it can protect
# the user-facing phone UI. Compile that heredoc here so harness regressions are
# caught before APK build or install.
python3 - "$ROOT/scripts/prove-phone-menu-ui.sh" <<'PY'
import pathlib
import sys

path = pathlib.Path(sys.argv[1])
lines = path.read_text(encoding="utf-8").splitlines()
marker = '    python3 - "$DUMP_LOCAL" "$ime_state" <<\'PY\''
try:
    start = lines.index(marker) + 1
except ValueError as exc:
    raise SystemExit(f"Phone plan regression guard failed: missing toolbar geometry Python heredoc in {path}") from exc
body = []
for line in lines[start:]:
    if line == "PY":
        break
    body.append(line)
else:
    raise SystemExit(f"Phone plan regression guard failed: unterminated toolbar geometry Python heredoc in {path}")
compile("\n".join(body) + "\n", f"{path}:assert_terminal_toolbar_geometry", "exec")
PY

echo "Phone plan regression guard passed"
